### ISSUE TITLE
Seed Viewing/Reusing

### ISSUE THREAD

**Issue by seijihariki** [zero01101/openOutpaint#101]
**Is your feature request related to a problem? Please describe.**
We almost forgot the feature that was requested on reddit for viewing/reusing the seed used for generation. 

**Describe the solution you'd like**
As the API does not provide this value, we can try locally generating a seed, and using that to send to the API when seed is set to  - 1.

**Comment by seijihariki** [comment]
This process could actually fix the set seed "more" generation (for now it creates copies of thr first batches)

**Comment by zero01101** [comment]
>As the API does not provide this value,

:D i get to show off something i know!! on the `_dream` response, yknow how we're returning data.images?  try adding 
```	
var responseSubdata = JSON.parse(data.info);
	console.log(
		"seed: " +
			responseSubdata.seed +
			"\nall seeds: " +
			JSON.stringify(responseSubdata.all_seeds) +
			"\nsubseed: " +
			responseSubdata.subseed +
			"\nall subseeds: " +
			JSON.stringify(responseSubdata.all_subseeds)
	);
``` 
right before returning data.images ;)

nothing against throwing in our own PRNG of course lol

**Comment by seijihariki** [comment]
That's cool! Can you do this one, then?

**Comment by seijihariki** [comment]
Didn't know it returned more than just the images themselves.

**Comment by zero01101** [comment]
i lied :D random seed reuse now in testing, there's a "U" button in the post-dream minitools that when hovered over shows the current seed and will send it to the seed input; also added the seed value to resource default titles
