### ISSUE TITLE
layer-based background removal

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#107]
**Is your feature request related to a problem? Please describe.**
it is absolutely _not_

**Describe the solution you'd like**
so like when i was talking about [difference globalcompositeoperation](https://github.com/zero01101/openOutpaint/pull/67#issuecomment-1336505519) and [failing at it in photoshop](https://github.com/zero01101/openOutpaint/pull/67#issuecomment-1338318790), i've since discovered what i meant was ["background subtraction"](
https://www.fabiofranchino.com/blog/implement-the-background-subtraction-with-canvas-and-js/) and i _still_ kinda think that'd be a nifty feature, like c'mon

**no actually _describe_ it dummy**  
oh uh so like if an in/outpaint dream or maybe even txt2img is requested with the "subtract background" option ticked, the following should occur:
 - all currently visible layers in the bounding box should be sampled to a new canvas or image
 - the dream is dreamed 
 - the user approves a dreamed image
 - the dream image has the magic done to it from the aforementioned article against that new canvas/layer from step 1ish, has the identical pixels from the currently visible layers removed, and is placed onto a new layer of its own
 
 the more i think about this, the more it sounds like it'll ONLY be useful for img2img because, uh, most people probably don't want a giant chunk of the "background" automagically smooshed into their new detail layer...

**Describe alternatives you've considered**
well i guess painstakingly erasing identical pixels would work if i wasn't impatient?

**Additional context**
i will 100% _try_ and almost certainly _fail_ to implement something like this myself, but uh, *ahem* don't let that stop anyone else from showing me who's boss ;)

**priority**
literally the lowest possible; like if there's an errant apostrophe in a readme 2 versions ago that's probably more important

**Comment by seijihariki** [comment]
I'll leave this one to you, then!

**Comment by zero01101** [comment]
i didn't forget about this i swear 

https://github.com/zero01101/openOutpaint/commit/02bf04c25734ae4156b637eda0b1cd5cc6a3d568

it... kinda works?  not great with img2img and _very bad_ with sketch tool lmao 

[bgremove.webm](https://user-images.githubusercontent.com/1649724/215359818-8a4e43b2-f97c-400c-9b23-6e9149992aa1.webm)

**Comment by zero01101** [comment]
https://github.com/zero01101/openOutpaint/wiki/Manual#dream and scroll down a bit?
janky but exists now
