### ISSUE TITLE
brushed masks follow expanded canvas to new x/y origins

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#117]
**Describe the bug**
after expanding the canvas upwards or to the left, any brushed masks use the new "0px origin" instead of where they're actually drawn

**To Reproduce**
- start a new canvas or use one you're already painting on
- press the leftward expand canvas button and expand it by 128 px
- draw a new brushed mask on the image and engage it with txt/img2img
- observe that it's too far left
- realize that this probably happens on the y-axis too and you're bad at troubleshooting properly
- expand the canvas 128px up
- notice that nothing in the example images got changed at all after doing that

**Expected behavior**
the modified result should be where the mask is drawn instead of being offset by the new x-axis "zero point"

**Screenshots**
![image](https://user-images.githubusercontent.com/1649724/209413207-dad59782-db26-40c3-ac2f-98a12173516d.png)
![image](https://user-images.githubusercontent.com/1649724/209413220-94fcf906-338e-4e08-93e4-d8edd6202fb1.png)
![image](https://user-images.githubusercontent.com/1649724/209413233-f6fb26dc-e0ad-405e-a9bc-b62aca277105.png)
--after expanding vertically--
![image](https://user-images.githubusercontent.com/1649724/209413377-5130a3d1-dc55-4453-ba04-25a78ccb8b9f.png)

**Desktop (please complete the following information):**

- OS: win10x64
- Browser: firefox 
- Version 108.0.1x64

**Comment by seijihariki** [comment]
On it

**Comment by seijihariki** [comment]
Strangely, this was a case of overcorrection rather than a lack of corrections.

I previously modified masking to work with a less magical version of the black magic, but after making the mask as magical as it is now, those corrections were moving things to the other side.

Simple commit incoming.

**Comment by zero01101** [comment]
lmao wtf i was literally going to look into this later and oh gee you fixed it in 5 minutes of noticing

**Comment by zero01101** [comment]
>I previously modified masking to work with a less magical version of the black magic, but after making the mask as magical

i just wanted to say i love this so so much
