### ISSUE TITLE
Add "Restore Face" option

### ISSUE THREAD

**Issue by wywywywy** [zero01101/openOutpaint#129]
**Is your feature request related to a problem? Please describe.**
Sometimes you have faces in your inpaint/outpaint. And without Codeformer or GFPGAN, the faces usually have artifacts. So I propose the "Restore Face" option from the API to be added.

**Describe the solution you'd like**
New "Restore face" checkbox under the "Stable Diffusion settings" panel.

**Additional context**
Face restore is already one of the parameters we can specify in the txt2img & img2img API call. So there should be no additional logic required.

**Comment by seijihariki** [comment]
Can you try the `testing` branch for now?

**Comment by wywywywy** [comment]
Sorry I don't see a Face Restore checkbox in the `testing` branch?

**Comment by zero01101** [comment]
should be under the stable diffusion settings; check that you're on commit https://github.com/zero01101/openOutpaint/commit/a95906dc8af2d760b1d5313dd8311fb325b58f36 and try reloading the page without cache?  

![image](https://user-images.githubusercontent.com/1649724/210019825-24c0f8a0-070d-4465-8e53-05bcd1138289.png)

**Comment by wywywywy** [comment]
Yea sorry I forgot that it does a submodule update back to the main branch every time it starts.

I just tested it and it seems to be working well!
