### ISSUE TITLE
It would be nice to be able to resize the image with a mouse scroll movement when pasting an image with Stamp image or Ctrl + v.

### ISSUE THREAD

**Issue by toyxyz** [zero01101/openOutpaint#131]
It would be nice to be able to resize the image with a mouse scroll movement when pasting an image with Stamp image or Ctrl + v. 
Currently, it is necessary to resize using Select image additionally, and there is a problem of selecting other images on the same layer together.
And is it possible to rotate the image as well?

**Comment by seijihariki** [comment]
Probably doable. Rotating... would be a bit of a pain, actually.

**Comment by seijihariki** [comment]
Hi, could you try the `rotate` branch?

Just go into the directory of openOutpaint (`extensions/<extension>/app` for extensions) and `git checkout rotate`.

If using the extension, DO NOT restart the webui after running this command, just reload openOutpaint via the 'Refresh openOutpaint' button.

**Comment by seijihariki** [comment]
It is now in main. If there are any issues with the current implementation, open a new issue.
