### ISSUE TITLE
windows-native .devtools scripts 

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#132]
**Is your feature request related to a problem? Please describe.**  
sorta but the problem is probably me

**Describe the solution you'd like**
windows-native scripts for `.devtools` folder because i hate NPM and don't want to think about it ever

**Describe alternatives you've considered**  
abandoning software development entirely

**Additional context**
i'm a weenie

**Comment by seijihariki** [comment]
Hi, I hate npm as well, and I use linus for development! haha

I just use vscode as my IDE and installed the prettier extension. We can of course still develop some windows scripts!

**Comment by zero01101** [comment]
well pfffft in that case i can pretty easily just run `git config core.hooksPath .githooks` manually from command prompt lmao :D
