### ISSUE TITLE
Metadata or log file with description of image design process

### ISSUE THREAD

**Issue by Kextrii** [zero01101/openOutpaint#133]
(The tool is really great as is! I'm enjoying using it a lot!)

It would be nice to see a line-by-line description of the process I used to create an image, so that I can learn which prompts and settings led to a good final image, for future reference.

**Describe the solution you'd like**
For each Dream or Img2img action that is successfully performed, create a line of text in a log file including:
- the current Prompt Text (positive and negative)
- name of Model file used (and Hypernetwork, if active)
- Seed
- Sampler
- Steps
- CFG
- Resolution
- Whether txt2img HRfix is turned on
- if img2img, include Denoising Strength
- (other relevant settings I might have forgotten about)

In case of a Mask being drawn, or use of Color Brush, or Layer manipulation, or any other actions, add a short line of text equivalent to what is recorded in the History bar.

(Optional: Remove log lines when its action is undone, but keep recently undone lines ready to add back in case of "redo". Alternatively, include the fact that "undo/redo" was used in the log file.)

When the user clicks "Save canvas", write out a log file with the same name as the image output file (different extension). Or, if the image file format is compatible, write the log text to the image metadata ("caption").

**Comment by seijihariki** [comment]
Sorry for taking so long!

Your idea of logging information about the edit history sent me through a rabbit hole and in the end I decided to implement a full session management system on top of this request!

For now (sadly) I have not implemented logging yet, but you can now save the current workspace state and load it later from the save file.

Now it is probably easier than ever to implement your request, so I will get to that tomorrow!

**Comment by seijihariki** [comment]
Should be on main already, so will be putting to eval.

**Comment by seijihariki** [comment]
Will be closing this issue as the feature has been implemented. If there are any changes you would like, @Kextrii, just send a message here or open a new issue!

**Comment by Kextrii** [comment]
Nice! It took me a minute to figure out that I needed to click on the scroll icon in the history sidebar. That's extremely helpful!

What about having a check box next to the "Save canvas" that would automatically save the log file at the same time as saving the image?

**Comment by seijihariki** [comment]
Will give this a look
