### ISSUE TITLE
Img2Img denoise strength bug?

### ISSUE THREAD

**Issue by bananasss00** [zero01101/openOutpaint#147]
**Describe the bug**
"Denoising Strength" **_below 0.7_** results in a blurry image.
_Used v1.5, v2.1[512] inpainting models with different samplers and steps_

**To Reproduce**

1. Set the 'Denoise Strength' level below 0.7.
2. Regenerate some area
3. See blurry square

**Expected behavior**
Same behavior as in WebUI-Inpainting

**Screenshots**
![изображение](https://user-images.githubusercontent.com/30229634/210332295-c36dde99-2db8-4217-abb4-fb5c6ecd53a9.png)

**Environment (please complete the following information):**

- Free Google-Collab (https://github.com/TheLastBen/fast-stable-diffusion)
- Browser and Version: [chrome 106.0.5249.103]
- Any browser extensions: Clean chrome without extensions
- Commit of openOutpaint: https://github.com/zero01101/openOutpaint/commit/bc853172f2dfd2c6845797bbca63db65b2ebce60
- Commit of A1111 webUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a1cf55a9d1c82f8e56c00d549bca5c8fa069f412

**Comment by zero01101** [comment]
this should be fixed in https://github.com/zero01101/openOutpaint/commit/15395d899d95466c013c2793a19ce457f7d6bd96 now; it was actually failing to set the inpaint type whatsoever and was falling back to "fill" mode which returns that sort of output
