### ISSUE TITLE
alerts are not visible

### ISSUE THREAD

**Issue by vladmandic** [zero01101/openOutpaint#151]
most modern browsers suppress `alert()` on page load, so critical messages do not even show up

for example, this is only visible in browsers console log as alert was suppressed by browser

> The host is online, but the API seems to be disabled.

why not use a div element in top-right to show messages and get rid of all alerts?

- OS and Version: Windows 11 with Chrome 108
- GPU: RTX3060
- Browser and Version: Chrome 108
- Any browser extensions: N/A
- Commit of openOutpaint-webUI-extension: 2fd0126454c7a836e41103311655f304772983fa (01/03/2023)
- Commit of A1111 webUI: b7deea47eeb033052062621b0005d4321b53bff7 (01/04/2023)
- How you interact with A1111 webUI: Local hardware

originally opened in <https://github.com/zero01101/openOutpaint-webUI-extension/issues/17>, but i think its better fitted here.

**Comment by seijihariki** [comment]
That is a thing I have considered since the beginning... Just continued ignoring the issue... I think it wouldn't be really hard. Will mark as good first issue for now.

**Comment by vladmandic** [comment]
bonus would be:
- use the same div for dream/upscale/save/whatever messages
- have it auto-clear on timer so last message is not stuck indefinitely

**Comment by seijihariki** [comment]
Hi, @vladmandic! I pushed some changed the other day that switch to a custom notification system for alerts. Confirmations were also migrated, but prompt() instances still not. Can you see it this seems to be an okay start?

**Comment by vladmandic** [comment]
@seijihariki i see the notification box in bottom left show up when i switch model, but its barely noticeable. still a good start.
btw, i don't see notifications if im using standard model instead of inpainiting one?

**Comment by seijihariki** [comment]
Notification should not have anything to do with the selected model, I think. I remember @zero01101 had done some changes to inpainting model detection, so he would probably know to answer that.

I will see what I can do so the notifications are more prominent.

**Comment by zero01101** [comment]
yeah, the only notification that should have anything to do with the selected model would be the first-time-online check alerting you if your currently selected model isn't Inpainting and offering you an option to switch to a detected Inpainting model

that API endpoint I added for checking unet counts isn't actually used anywhere yet, it just kinda hangs out being pointless lol; it's actually pretty slow :(

**Comment by seijihariki** [comment]
Will be closing this issue for now... We can reopen it in the future.
