### ISSUE TITLE
Rotate Canvas

### ISSUE THREAD

**Issue by guzuligo** [zero01101/openOutpaint#156]
Some models are trained on new stuff that look good when they are up straight. Once rotated, the model miss it up.

A great feature would be if we could rotate the canvas for the model so it gets it right.

**Comment by guzuligo** [comment]
Ok, I did `git checkout rotate` and see nothing
Did, `git pull` and couldn't find it
I decided to restart the webui, but still nothing 😅

`
From https://github.com/zero01101/openOutpaint
   e2afee3..b590b6d  rotate     -> origin/rotate
Updating e2afee3..b590b6d
Fast-forward
 index.html                     |  14 ++--
 js/config.js                   |  15 +++++
 js/initalize/debug.populate.js |   2 -
 js/ui/tool/dream.js            |  42 +++++++++++-
 js/ui/tool/generic.js          |  75 +++++++++++++++++-----
 js/ui/tool/select.js           | 123 ++++++++++++++++++-----------------
 js/ui/tool/stamp.js            | 142 ++++++++++++++++++++++++++++++++++-------
 7 files changed, 305 insertions(+), 108 deletions(-)
`

**Comment by guzuligo** [comment]
Where should I find the rotate option?

**Comment by seijihariki** [comment]
Now you should run git checkout rotate and reload the openOutpaint page

**Comment by guzuligo** [comment]
Ok, it seems for some reason, my browser isn't clearing the cache even after i delete the cache.

Now I see scale option on stamp. Works fine. But can't find anything about rotate.

Though, stamp is a big tricky to use when you want to stamp layers behind as it blocks all layers
![image](https://user-images.githubusercontent.com/4189008/212233849-90b7700c-efff-456c-ae1f-061e3fb9fd64.png)

**Comment by seijihariki** [comment]
For stamp rotating is with LMB drag (wheel finetune is shift+wheel). We can try implementing something like select peek for stamp...

**Comment by seijihariki** [comment]
Rotating is also possible using the select tool itself.

**Comment by guzuligo** [comment]
How? Can't find the option ... or the hot key

**Comment by seijihariki** [comment]
No hotkey needed... Dragging with the left mouse button on stamp just rotates the stamp automatically

**Comment by seijihariki** [comment]
Select tool has a new rotate handle.

**Comment by guzuligo** [comment]
Where? In the middle? Corner?

**Comment by guzuligo** [comment]
It just scales:
![image](https://user-images.githubusercontent.com/4189008/212235197-9056bb9c-47b6-4c7d-87a7-6edc738017a0.png)

**Comment by seijihariki** [comment]
You are not in the rotate branch apparently:

https://user-images.githubusercontent.com/7552751/212235442-e0211f1f-e6b4-4581-98a0-ae63c2d0193c.mp4

**Comment by seijihariki** [comment]
Let me test with chrome

**Comment by seijihariki** [comment]
Chrome also seems to work:

https://user-images.githubusercontent.com/7552751/212235766-e48c2dd0-a53d-4920-99c8-a8b32101d0e3.mp4

**Comment by guzuligo** [comment]
Ok, it seems I opened the browser that doesn't clear cache 😅
Now I see it 🥲

**Comment by seijihariki** [comment]
Ok! Oh, and shift when rotating snaps to multiples of 45 degrees.

**Comment by guzuligo** [comment]
Yup! It solves a lot of problems 😱😂
![image](https://user-images.githubusercontent.com/4189008/212236777-a067c0f8-85ce-4ca7-bb6a-ac764e3cb028.png)

**Comment by guzuligo** [comment]
YES!!! Now even I fixed the damaged ones!
![image](https://user-images.githubusercontent.com/4189008/212237312-374e02fc-7ab5-48f5-8dfd-775d248115c0.png)

Fixing is not as easy as rotating the img2img cursor. But, still works as charm. And has more applications than just the cursor rotation 👍👍
