### ISSUE TITLE
Don't launch on TheLastBen Colab

### ISSUE THREAD

**Issue by cerarslan** [zero01101/openOutpaint#158]
**Describe the bug**

**To Reproduce**

I did this step 

In your webUI installation directory, open webui-user.bat/sh in a text editor, and ensure the line starting with set COMMANDLINE_ARGS= contains the following: --api --cors-allow-origins=http://127.0.0.1:3456, then save the file.

but I couldn't found/understand this step NOTE: the commandline flag --gradio-debug disables custom API routes and completely breaks openOutpaint. if applicable, please remove it from your COMMANDLINE_ARGS before running openOutpaint.

**Additional context**

openOutpaint init
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/scripts/main.py", line 40, in <module>
    print(run(f'"{git}" -C "' + scripts.basedir() +
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/launch.py", line 64, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "git" -C "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 1
stdout: <empty>
stderr: fatal: destination path '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/app' already exists and is not an empty directory.
fatal: clone of 'https://github.com/zero01101/openOutpaint.git' into submodule path '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/app' failed
Failed to clone 'app'. Retry scheduled
fatal: destination path '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/app' already exists and is not an empty directory.
fatal: clone of 'https://github.com/zero01101/openOutpaint.git' into submodule path '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/app' failed
Failed to clone 'app' a second time, aborting

**Comment by seijihariki** [comment]
Hi! have you added the `%cd`?

Yours seems to be a different problem, but [here](https://github.com/zero01101/openOutpaint-webUI-extension/issues/11#issuecomment-1365569869) is a quick fix for some problems TheLastBen colab users were facing with extensions.

**Comment by seijihariki** [comment]
For now, a fix is to delete on GDrive the folder SD/extensions/the extension/app and run the webui again

**Comment by cerarslan** [comment]
thank you! Now I can launch and see extension tab on webui but now I see  {"detail":"Not Found"} error. Sorry to bother you my newbie questions :(

**Comment by seijihariki** [comment]
![image](https://user-images.githubusercontent.com/7552751/210880300-d9dad837-517d-4749-a933-f01740684afd.png)

The

```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
```

command should be added before the last `try:` tag.

Remember to also enable the API:

![image](https://user-images.githubusercontent.com/7552751/210880725-712100b2-a3d7-4687-b73c-031e16567460.png)

**Comment by seijihariki** [comment]
If that still didn't work, delete the whole extension from your gdrive and reinstall it from the webui extensions tab.

**Comment by cerarslan** [comment]
After that Enable_API = True and %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui command, I delete extensions folder and reinstalled the extension and it worked now. Thx so much my friend!

**Comment by seijihariki** [comment]
No problem! Glad to help.

For Colaborators: It seems the installation process has been... A bit unstable recently. Will keep an eye on this and close the issue for now.
