### ISSUE TITLE
Add functionality to remove a single image from generated images list

### ISSUE THREAD

**Issue by JamesDooley** [zero01101/openOutpaint#164]
Currently when generating images there is no option to dismiss a single image.  You can either select one image to replace what is on the screen or delete all of the generated images.  It would be nice if there was a button to remove the currently displayed image from the list.  This way if I am comparing 5 images, and I know that I do not like one I can just remove it outright.  This makes it easier to compare the differences between images I do like.

This would further add value to the generate more button, since I could keep a few images that I like and remove the rest and then generate some additional images to see if there is something I like better.  Without this you just end up with a lot of mixed images that you may or may not like. Because of this I generally do not use the button to generate additional images.

Alternatively you could rate / star generated images, but I think that would be more work than it is worth.

**Comment by zero01101** [comment]
should be implemented as of https://github.com/zero01101/openOutpaint/commit/bf21c19ae352800d9e1b37bb490e817b6848e533
