### ISSUE TITLE
[Bug]: It complains it's offline when i click.

### ISSUE THREAD

**Issue by DuckersMcQuack** [zero01101/openOutpaint#171]
### What happened?

I open openoutpaint, load a model, tested OG 1.4, and it just says offline when i click. Even with default prompts as a test.

### Steps to reproduce the problem

Simply launch and click anywhere. 

### What should have happened?

Generating outpaint.

### Commit where the problem happens

Doesn't say. All my installed extensions says "unknown". Downloaded it yesterday.

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

**Comment by zero01101** [comment]
is webUI running on a different server/address?  there are supposed to be checks but depending on your browser addons, something may be blocking the request somewhere, hence we ask in the form what extensions you use.

are you running webUI with the `--api` flag enabled?

**Comment by zero01101** [comment]
hey @DuckersMcQuack , did you ever get anywhere else with this?

**Comment by P8ntBal1551** [comment]
I am having the same issue.

I downloaded and installed it through the A1111 extensions tab. I tried it on both firefox and chromium and it give the offline error on both. I have the "--api" option set in webui-user.sh (I'm on Linux). 

a couple weird things, though. When I start A1111, I get the line

```
Launching Web UI with arguments: 
No module 'xformers'. Proceeding without it.
```

here is my webui-user.sh

```
#!/bin/bash
#########################################################
# Uncomment and change the variables below to your need:#
#########################################################

# Install directory without trailing slash
#install_dir="/home/$(whoami)"

# Name of the subdirectory
#clone_dir="stable-diffusion-webui"

# Commandline arguments for webui.py, for example: export COMMANDLINE_ARGS="--medvram --opt-split-attention"
export COMMANDLINE_ARGS="--api"

# python3 executable
#python_cmd="python3"

# git executable
#export GIT="git"

# python3 venv without trailing slash (defaults to ${install_dir}/${clone_dir}/venv)
#venv_dir="venv"

# script to launch to start the app
#export LAUNCH_SCRIPT="launch.py"

# install command for torch
#export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"

# Requirements file to use for stable-diffusion-webui
#export REQS_FILE="requirements_versions.txt"

# Fixed git repos
#export K_DIFFUSION_PACKAGE=""
#export GFPGAN_PACKAGE=""

# Fixed git commits
#export STABLE_DIFFUSION_COMMIT_HASH=""
#export TAMING_TRANSFORMERS_COMMIT_HASH=""
#export CODEFORMER_COMMIT_HASH=""
#export BLIP_COMMIT_HASH=""

# Uncomment to enable accelerated launch
#export ACCELERATE="True"

###########################################
```

**Comment by P8ntBal1551** [comment]
I'm at work right now, so I can't check all that, but I can tell you that firefox's console reports a 404 on the GET request to /sdapi/v1/options

I also have a message that says 

> The host is online, but the API seems to be disabled.
> Have you run the webui with the flag '--api', or is the flag '--gradio-debug' currently active?

How would one check a standalone install? I assume this involves installing the full application?

**Comment by zero01101** [comment]
>I'm at work right now, so I can't check all that[...]yet

no rush of course :) 

>firefox's console reports a 404 on the GET request to /sdapi/v1/options

yeah that's definitely gonna be the crux of the issue; if webUI isn't exposing the API endpoints for some reason, anything that relies on it (like openOutpaint) will fail to operate.  your `webui-user.sh` params _look_ right to me but my main usage is windows; anecdotally, on my linux build i do set my options in `webui-user.sh` but i actually just run `webui.sh` which applies the settings from the user script anyhow... 

>How would one check a standalone install? I assume this involves installing the full application?

not sure what you mean by "full application"- by standalone install you mean the usual clone of A1111 webUI onto a machine in your house (or under your direct control) with a dedicated GPU, right?  that alert you're referencing is referring to the commandline flags in your webui user script

**Comment by P8ntBal1551** [comment]
I'm a dumbass.

K, so, somewhere in the initiation of the webui, it should run that .sh file. It doesn't.
All I had to do was run the export in the file myself. I kept thinking that it couldn't be that easy and dismissing it.

It's nothing to do with your add-on. You keep being awesome. A1111 needs to fix the init to actually do the thing it needs to do.

**Comment by zero01101** [comment]
you want to hear dumbass, i clearly already forgot i wrote a post including the words "standalone install" referencing the non-extension version of openOutpaint which would also contextually explain "full application" which is technically a submodule in the extension already but ANYway 🤦

**Comment by Gagelee** [comment]
> is webUI running on a different server/address? there are supposed to be checks but depending on your browser addons, something may be blocking the request somewhere, hence we ask in the form what extensions you use.
> 
> are you running webUI with the `--api` flag enabled?

Hi, I also encountered the offline problem, and empty stable diffusion settings.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/19219684/226428069-199f8bef-36a4-40c9-8449-31d009749a7e.png">
Is it becuase I run the webui on a remote server and using ssh tunnel to open the webui on my laptop? would you please tell me how to fix this?

**Comment by zero01101** [comment]
hey @Gagelee, if you hover your mouse over the yellow indicator section  
![image](https://user-images.githubusercontent.com/1649724/226492206-77f98f91-f78d-4e62-83b4-d55a789fb6aa.png)
it should either display `API` or `CORS` depending on what isn't responding right - i've never even considered much less tried to run SD over SSH tunneling but the yellow indicator suggests that the server is contactable, just not responding to our requests.  the [manual > main](https://github.com/zero01101/openOutpaint/wiki/Manual#main) section explains the indicators at the bottom.

i'd guess you're missing either the `--api` flag (or `--cors-allow-origins` if using non-extension standalone) as mentioned [here](https://github.com/zero01101/openOutpaint/wiki/Manual#webui-launch-script--commandline_args)

**Comment by Gagelee** [comment]
> have you tried running the webui-user.sh file before starting A1111?

I thought the webui-user.sh is just for settings, and the webui.sh launches the whole webui so I just bash webui.sh. The yellow indicator says that API seems disabled, but I have using the api flag, here is my webui-user.bat commanlin

set COMMANDLINE_ARGS=--precision full  --medvram --no-half-vae --disable-nan-check --opt-split-attention --PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9 --api
