### ISSUE TITLE
[Bug]: Copying selection to clipboard no longer working?

### ISSUE THREAD

**Issue by ribawaja** [zero01101/openOutpaint#174]
### What happened?

I updated the openOutpaint a1111 plugin a few days ago (looks like commit 72f4e27), and now I'm noticing that I can no longer Ctrl-C images to the clipboard after selecting them with the S tool. I've tried toggling the "Use clipboard" icon in the context menu, but that doesn't make a difference.
Is it possible something broke here recently?

### Steps to reproduce the problem

Create an image, go to the "Select image" tool, drag to select the image, press Ctrl-C to copy.
Go to another application and try to paste with Ctrl-V -- the clipboard is empty.

### What should have happened?

Image should have been copied to clipboard

### Commit where the problem happens

72f4e27

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

lastpass, bitdefender

### AUTOMATIC1111 webUI Commandline Arguments

--autolaunch --api

**Comment by seijihariki** [comment]
Probably broke on select tool overhaul. Will push a fix as soon as possible.

**Comment by zero01101** [comment]
lol yep was just about to confirm that it seems to be on https://github.com/zero01101/openOutpaint/commit/ec4054529cc81a54a8f8d0f3b95f20473855ac6a unfortunately :/

**Comment by seijihariki** [comment]
Fixed.

**Comment by ribawaja** [comment]
It works now. Thanks guys!

**Comment by ribawaja** [comment]
@seijihariki, @zero01101  Also, I'm using the eager generation thing a lot, and it would be nice if there were a way to mark images and cycle through just the marked ones, for the case where user has generated dozens of inpaintings and is trying to decide between two or three that are far apart in the list. I may try to tackle this in the next couple weeks if I have time, suggestions welcome ahead of time, or you can wait to see what I come up with.

**Comment by seijihariki** [comment]
You can delete only the unwanted images, not sure if that is a valid alternative, at least for now.

**Comment by ribawaja** [comment]
Oh that's interesting, I didn't notice that before. So instead of scrolling through the list, prune the list with '-' as you go, skipping over the good images with mouse wheel. I'm going to try doing it that way for a while and see how it goes. Thanks!
