### ISSUE TITLE
[Bug]: Mask brush sometimes incorrectly scales when zooming in or out with mousewheel

### ISSUE THREAD

**Issue by artreloaded** [zero01101/openOutpaint#179]
### What happened?

I think I was able to narrow down this bug thats been bothering me for a while.

Browser: Chrome
OS: Win10

I have a window open on a big WQHD screen, and when I start the webui I resize it (often after opening openOutpaint). Then I usually outpaint or inpaint something and I zoom and click and brush. Regular workflow. But after some time the mask brush paints in a different size than what is shown, and when I zoom in or out sometimes the painted area is bigger or smaller than the shown area on the cursor and this can be a bit irritating.

I was thinking maybe the initial resizing of the openOutpaint window was causing this, but it just starts after some time and it stays even after switching tabs in A1111

![Annotation 2023-01-21 093040](https://user-images.githubusercontent.com/123234324/213858892-c46eb79a-9ed7-4da0-87be-ce14688cf8b3.png)

### Steps to reproduce the problem

Its in the description

### What should have happened?

Synchronized paint area with cursor area

### Commit where the problem happens

6889affcade60bcac8c92e1423277ef3428cc665

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

Nothing that should be relevant

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --api

**Comment by seijihariki** [comment]
That's weird. Will give this a look.

**Comment by seijihariki** [comment]
Can confirm. Zoom was not calculated properly. Fix now on main.
