### ISSUE TITLE
[Feature Request]: Symmetrical Outpainting

### ISSUE THREAD

**Issue by CJohnDesign** [zero01101/openOutpaint#184]
### Is your feature request related to a problem? Please describe.

Images of the problem I'm running into:
https://www.reddit.com/r/StableDiffusion/comments/10jprya/how_do_i_get_symmetrical_outpainting/

### Describe the solution you'd like

A checkbox that allows the outpainted area to be symmetrical.

### Proposed workflow

* User can select the symmetrical check box
* If checked, expanded area matches on both sides
** Might require Left/Right or Up/Down only

* Flow for expanding an image left and right:

* 256px of space added to the left side of the canvas
* X steps happen
** suggested 2-4 steps
* Copy the 256x512 image
* Add 256px to the right of the canvas
* Flip and paste in the copied image
* Repeat until done
* Optionally allow X steps at the end to remain on respective side
** Allows for unique features to appear

### Describe alternatives you've considered

Currently, I'd have to photoshop one side onto another. 

### Additional context

Also posted here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7147

**Comment by zero01101** [comment]
i think this is _exactly_ what you're looking for as far as mid-diffusion processing? https://github.com/comfyanonymous/ComfyUI/commit/69df7eba94edd8eee430374a380de15e54ab1f2c
