### ISSUE TITLE
[Bug]: Layers seem to jumble content/position 

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#185]
### What happened?

so i added a silly little convenience option to generate all dreams onto a new layer and it seems to have exacerbated an issue i THOUGHT i noticed previously but could never verify until now

basically just enable the autolayer option, generate an image, then start outpainting - eventually previous layer seams will "pop out" - it's sort of difficult to see in the gif (easier full-res) but there's a few instances in which earlier dream layers' edges suddenly become very visible

![ezgif-1-e1dc124ecf](https://user-images.githubusercontent.com/1649724/215274991-423c7755-b439-4d10-800c-6b62b3e85f7f.gif)

### Steps to reproduce the problem

0. `git checkout manual-scripts`
1. enable "new layer per dream" option
2. create any arbitrary dream
3. outpaint repeatedly 

### What should have happened?

layers should stay in their lane!!! >:( lol 

### Commit where the problem happens

ok honestly not sure as i THINK this has occurred for a while?

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

noscript, enhancer for youtube, greasemonkey, downthemall, facebook container, multi-account container, stream detector, kde plasma integration

### AUTOMATIC1111 webUI Commandline Arguments

`--ckpt-dir "E:\storage\stable diffusion models" --gfpgan-model GFPGANv1.4.pth --listen --autolaunch --deepdanbooru --xformers --api --api-log --enable-insecure-extension-access --cors-allow-origins=http://127.0.0.1:1180,http://127.0.0.1:3456,http://localhost:1180,http://localhost:3456,http://192.168.130.61,http://192.168.101.41:3456,https://zero01101.github.io,http://localhost:7860,http://192.168.120.20:3456`

**Comment by seijihariki** [comment]
_syncLayers should be fixed now on manual-scripts

**Comment by zero01101** [comment]
confirmed and many thanks as usual
