### ISSUE TITLE
[Bug]: cropped options toolbox

### ISSUE THREAD

**Issue by Raivshard** [zero01101/openOutpaint#187]
### What happened?

the options toolbox is cropped off.

### Steps to reproduce the problem

open the gear icon / config

### What should have happened?

it should not be cropped

### Commit where the problem happens

I have no idea where to find that information. All I have is the

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

all the security extensions are disabled for the webUI. only free download manager has access

### AUTOMATIC1111 webUI Commandline Arguments

--xformers --autolaunch --medvram --opt-split-attention --api --opt-channelslast --cors-allow-origins http://localhost:5173 --gradio-img2img-tool color-sketch --ckpt-dir 

### Additional information

https://i.imgur.com/Og182pT.png

**Comment by zero01101** [comment]
hm, i know the config window code has given me a bit of grief getting it to size properly in the past, but i can't confirm that happening on chrome (nor firefox) 109 for win10x64 in either standalone nor extension; do you have a different browser you could check it in?

![image](https://user-images.githubusercontent.com/1649724/215292959-29e38979-50c4-4794-9550-09639e95f47b.png)

**Comment by Raivshard** [comment]
tested on Edge, which is chromium-based, and then firefox. same problem in edge, but it worked fine in firefox

**Comment by seijihariki** [comment]
Cannot really replicate the issue on chromium even with an abysmally small window size:

![image](https://user-images.githubusercontent.com/7552751/215306798-a6d31892-26b5-42d2-9889-86367155ad34.png)

Can you tell us your browser version?

**Comment by zero01101** [comment]
lol i was literally just about to post this 
![image](https://user-images.githubusercontent.com/1649724/215307022-218b8f2c-8b57-4a37-bbf7-f294f8f82218.png)

**Comment by Raivshard** [comment]
> Cannot really replicate the issue on chromium even with an abysmally small window size:
> 
> ![image](https://user-images.githubusercontent.com/7552751/215306798-a6d31892-26b5-42d2-9889-86367155ad34.png)
> 
> Can you tell us your browser version?

window size and browser version won't affect this, as it is specifically a scaling issue which occurs across many different apps when they are not streamlined for scaling

**Comment by seijihariki** [comment]
By scaling, do you mean this?

![image](https://user-images.githubusercontent.com/7552751/215308213-28033c1c-683d-453f-a5b8-236b92fbed99.png)

If so, would you mind giving us the zoom level you have?

**Comment by zero01101** [comment]
ugh lmao i actually even tried doubling windows display scaling up to 200% and it was _unpleasant_ but still no issue with config window :/ 

![image](https://user-images.githubusercontent.com/1649724/215309867-8838fa6f-1fd0-4a0f-be0e-ffef2d480ab9.png)

**Comment by seijihariki** [comment]
@Raivshard Check the new branch `config-iface-overhaul`. It should be more resistant against whatever is causing your issue.

**Comment by seijihariki** [comment]
As no updates were provided, will be closing this issue.
