### ISSUE TITLE
[Feature Request]: erase opacity and automatic layers

### ISSUE THREAD

**Issue by Raivshard** [zero01101/openOutpaint#188]
### Is your feature request related to a problem? Please describe.

Erase function of the brush tooldoes not inherit the opacity setting. 

Also, there's no option to delete only what you add with the brush tool, so it just stays there on the image unless you want to delete everything.
### Describe the solution you'd like

inherit the opacity setting

automatically put all brush tool painting on a sub-layer that still intereacts
have one delete tool for image data and another for the brush tool

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Describe alternatives you've considered

...

**Comment by seijihariki** [comment]
First one can be easily done, and it makes sense it would function that way. Second will be added as an optional setting to be enabled from the options menu.

**Comment by seijihariki** [comment]
Partially done on [`seijihariki/issue188`](https://github.com/zero01101/openOutpaint/tree/seijihariki/issue188).

**Comment by zero01101** [comment]
should be implemented in https://github.com/zero01101/openOutpaint/commit/c0e936f2166e8d055a88a30911d57d7094a79a74, be sure to enable automatic layers in the options gear menu :)
