### ISSUE TITLE
[Feature Request]: stamp mirroring option

### ISSUE THREAD

**Issue by todstelzer** [zero01101/openOutpaint#193]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

Hello,
would it be possible to add a mirror command when using the stamp feature?

![grafik](https://user-images.githubusercontent.com/67606371/215312257-afbdbc5b-fbc9-489b-8889-57db44f53d56.png)

### Proposed workflow

-

### Describe alternatives you've considered

Have to use Photoshop. But that's an extra step i would like to avoid if possible.

**Comment by seijihariki** [comment]
On branch [`seijihariki/issue193`](https://github.com/zero01101/openOutpaint/tree/seijihariki/issue193).

**Comment by seijihariki** [comment]
On main now

**Comment by seijihariki** [comment]
Closing as completed for now. There is both a button for mirroring, but the '=' key also should work for inverting. If there are any issues with the current implementation, please send a message here.
