### ISSUE TITLE
Border with img2img erroneous

### ISSUE THREAD

**Issue by grummelgrisgram** [zero01101/openOutpaint#194]
### What happened?
The border seems to drastically influence the generated content, even the one not touching the border. For more detail, see below.

### Steps to reproduce the problem
See below.

### What should have happened?
Border should not influence the content, the content should still be unrelated to source image with "Denoising Strength" parameter set to 1. In general, I should still be able to influence the content, it should not (nearly) only be influenced by the present image if a border is set.
See below for more detail.

### Commit where the problem happens
Current state, a0e7608.

### What platforms do you use to access openOutpaint?
Windows.

### What browsers do you use to access the UI ?
Brave, same with Chrome.

### Browser Extensions/Addons
n.a.

### AUTOMATIC1111 webUI Commandline Arguments
--listen --enable-insecure-extension-access --xformers --api

### Additional information

There seems to be a bug in the "Border Mask Gradient" feature in combination with img2img.
I expect this to behave like the following:

a) If the border size ("Keep Border Size") is set to 0 and "Border Mask Gradient" is disabled, simply the whole cursor size should be updated.
This works as expected as you can see here (with Denoising Strength set to 1 to get an "unrelated image"). Although it does not seem to be 100% unrelated... But at least no border is considered obviously:

Source image right before generating:
![image](https://user-images.githubusercontent.com/22403961/217058878-e504b0e8-f324-4487-a945-513ad522ca37.png)
Result:
![image](https://user-images.githubusercontent.com/22403961/217058926-1bdb057d-613f-40bc-8e27-e048eeadb93f.png)

b) If the border size ("Keep Border Size") is set to 64 and "Border Mask Gradient" is still disabled, the border is expected to not be updated. But the rest of the cursor should be updated, similar to case (a) where the whole cursor content was updated.
This is **not** working as expected, see:
![image](https://user-images.githubusercontent.com/22403961/217059422-b8439ce5-17a0-48a5-9681-0012256239c6.png)
Please note, that the border is not touched as expected and the rest of the cursor **is** modified. But this is by no means a "Denoising Strength" of 1 here. Instead, it is only modified in a very minor way! I'd expect something similar to (a) here instead.

c) If the border size ("Keep Border Size") is set to 64 and "Border Mask Gradient" is enabled, a similar image as in (a) would be expected but the border should be faded to the original image.
This is also **not** working as expected, see:
![image](https://user-images.githubusercontent.com/22403961/217059948-e54b46ab-9e97-4c09-b4fe-cf5c32a36247.png)
Also here, there are minor updates inside the cursor but with "Denoising Strength" set to 1, I'd expect a lot more.

Since I only changed the two border parameters ("Keep Border Size" and "Border Mask Gradient") between case (a) and (b) resp. (c), I think something is going wrong with the border calculation here...

**Comment by zero01101** [comment]
so out of curiosity, would you pop open the debug info tab and enable the "toggle debug" setting and try that again with one of your non-working setups?  it should download an image with both your image and the mask generated and sent to the API - if you'd be so kind as to crop those into two separate images and try them in the standard A1111 img2img tab?  

i completely agree with your expectation and premise, but it seems to operate this way in webUI itself :/  

![image](https://user-images.githubusercontent.com/1649724/217110975-ce896eea-c314-45ec-8e3b-3de7e426704e.png)

**Comment by grummelgrisgram** [comment]
Thanks for the quick response, zero01101 - and the marvelous openoutpaint nevertheless!
You're right, I have the same problem there at the standard img2img.
So, what can we do? Submit a similar issue at automatic1111 UI?

**Comment by zero01101** [comment]
thanks :) the grand majority of the marvelousness is @seijihariki's doing but i appreciate the kind words :D 

i _presume_ A1111's repo would be where to submit the issue, but i genuinely don't know if it might be further upstream, like in the parent compvis stable diffusion or something :/

**Comment by grummelgrisgram** [comment]
Thanks :-)

I submitted the issue to automatic1111 repo:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7611

So this issue here could probably be closed I guess.

**Comment by seijihariki** [comment]
Hi! Hey, @zero01101 have been a bit offline due to traveling for work. Will be closing this issue, then!

@grummelgrisgram, if you have any more issues, we'll be glad to help you solve it.

**Comment by zero01101** [comment]
>Hey, @zero01101 have been a bit offline due to traveling for work.

welcome back! no worries at all of course and hope you got to go somewhere new and interesting at least :D i've been kinda swamped here too so just basically dropping some [garbage](https://github.com/zero01101/openOutpaint-webUI-extension/commit/ecc8ff7072e4bd6c46fc6dc146ea2e412db0c1ac) [here](https://github.com/zero01101/openOutpaint/commit/e6c54d4b56ce0ad8abbbb9998bd0eb964f1e6638) and [there](https://github.com/zero01101/openOutpaint/commit/02bf04c25734ae4156b637eda0b1cd5cc6a3d568) when i get a chance ;)
