### ISSUE TITLE
[Feature Request]: to be able to save the settings for the img2img and Dream sections

### ISSUE THREAD

**Issue by mpmo10** [zero01101/openOutpaint#195]
### Is your feature request related to a problem? Please describe.

Problem is I don't like the default settings. So every time I change the settings and then close openoutpaint, the settings reset to the default.

### Describe the solution you'd like

To either keep the settings unchanged from the last time we opened openoutpaint (best option) or at least let the settings be saved/exported when we use the new "Export Workspace" button. Below are the settings i'm talking about (They are in the Dream and img2img tabs):

![2023-02-06 23_53_58-openOutpaint 🐠](https://user-images.githubusercontent.com/52265226/217071983-c0a81e11-18e5-4ede-9c81-751a951c8565.png)
![2023-02-06 23_54_47-openOutpaint 🐠](https://user-images.githubusercontent.com/52265226/217072003-397b795c-9833-4e64-bae2-5098966370b6.png)

### Proposed workflow

As I said above, either keep the settings unchanged from the last time we opened openoutpaint or at least let the settings be saved/exported when we use the new "Export Workspace" button

### Describe alternatives you've considered

No alternatives available other than manually changing the settings again and again

**Comment by zero01101** [comment]
hey, so i have a bit of bad news; those context parameters are essentially built into the page DOM on the fly; you may have also noticed that they don't really have localstorage settings persistence like main parameters do.  

essentially, i'm not saying it's impossible or that it'll never happen, but it's probably not going to happen particularly _soon_ as it'd kind of take rewriting how the context controls and their parameters are generated :/

**Comment by seijihariki** [comment]
This... Would not be that hard, actually. Will look into implementing this, but I'll be a bit busy for the week. I may or may not do something about this soon.

Other issues have for now a higher priority, as they have been here for quite a while.

Still, this is quite doable, so will be reopening this issue.

**Comment by seijihariki** [comment]
Give this a look!

**Comment by seijihariki** [comment]
This should be working. Will be closing as completed, if you have any questions/changes, we can reopen this issue.
