### ISSUE TITLE
Code AutoFormatting

### ISSUE THREAD

**Issue by seijihariki** [zero01101/openOutpaint#20]
Hey, I think it would be of great interest of the project for us to define some code formatting guidelines to allow for usage of prettier or eslint for auto-formatting. I think this could help keep the code clean.

We can keep many of our current trends (semicolon use, although currently not consistent) and 4 space indentation, but I think some limits of line lengths could help make the code a bit more readable, for example.

**Comment by zero01101** [comment]
yeah consistency and clean code are NOT some of my strong points lol
good plan though 👍

**Comment by Kalekki** [comment]
https://github.com/marketplace/unibeautify-ci or a similar Github action could do the trick.

**Comment by seijihariki** [comment]
Thats actually the point!
 
We should have some guidelines to configure an automatic formatter so we don't have to worry about that anymore!

I'm also pretty bad at this without some magic autoformatting.

**Comment by zero01101** [comment]
prettier looked nice :) i'm shamefully amateurish at Business-Quality Servoce Software™ like github and associated actions, so i've got some learning to do regarding setting up the action, but https://github.com/zero01101/openOutpaint/commit/5e49d1806e636aab44b0c8c3d348aac491bf4496 is at least a start :)

**Comment by zero01101** [comment]
i _think_ this works now? 🤞
