### ISSUE TITLE
[Bug]: ghosts of deleted layers haunt future generations

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#201]
### What happened?

content in deleted layers affects future dream generation and it's spooky because i banished these evil spirits yet still they remain

### Steps to reproduce the problem

- generate a dream and create a new layer
![image](https://user-images.githubusercontent.com/1649724/219881522-093b9ca1-fc5a-4cfd-ac04-491bdaea8a9b.png)
- outpaint on top of it, accepting an image causing the new layer to contain pixel data
![image](https://user-images.githubusercontent.com/1649724/219881571-0528ec80-e0b6-4440-a024-43ae47eba1b9.png)
- delete the new layer and toggle debug mode to enabled, and outpaint again, overlapping the region that would have been in the layer you just deleted
![image](https://user-images.githubusercontent.com/1649724/219881626-798ff97c-742b-47b7-9f37-79a61597fb1c.png)
- receive spooky ghost in debug png and resultant outpaint, uh, output
![image](https://user-images.githubusercontent.com/1649724/219881646-e8375813-d157-40ca-ba1e-2e4649f1373e.png)
![image](https://user-images.githubusercontent.com/1649724/219881662-46706685-837f-4680-987c-268dd1395767.png)

### What should have happened?

NO GHOSTS 
2SPOOKY

### Commit where the problem happens

observed on 6bc3043fc34bde27f33c536fb3987d799371c531, likely occurrs much earlier

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

seriously a lot but they're not doing this

### AUTOMATIC1111 webUI Commandline Arguments

yep

### Additional information

👻

**Comment by seijihariki** [comment]
@zero01101 it seems to be an issue in the layer management lib.

![Screenshot_2023-02-18-15-32-08-768_com.github.android.jpg](https://user-images.githubusercontent.com/7552751/219882783-4409dd40-cd28-49f9-8752-e5c8aa771d9f.jpg)

I'm currently not with a computer, so if you can, there you need to change the hide() and unhide() functions to set `this.state.visible = true` and false respectively instead of setting the display variable manually.

**Comment by zero01101** [comment]
confirmed ghostbusting, very muchly obliged!
