### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by HappyCatKitten** [zero01101/openOutpaint#202]
### Is your feature request related to a problem? Please describe.

Can we have a zoom control? (scroll wheel zoom too)

### Describe the solution you'd like

just a simple zoom

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Describe alternatives you've considered

Not zooming

**Comment by HappyCatKitten** [comment]
done

**Comment by seijihariki** [comment]
Camera zooming is available with Ctrl (Ctrl + mouse wheel scroll)

**Comment by seijihariki** [comment]
Will be closing for lack of details for now... Just send a message here and we can reopen this issue!
