### ISSUE TITLE
[Bug]: OpenOutpaint broke ffmpeg

### ISSUE THREAD

**Issue by Deadstarrr** [zero01101/openOutpaint#206]
### What happened?

I installed openoutpaint from within the automatic1111 webui and after doing that I realized that openpose no longer works. I deleted the openoutpaint extension folder, but it seems to have messed up other files because now I'm getting the following error that I never used to get when I add a pose and try to use txt2image:

File "C:\Stable Diffusion Files\stable-diffusion-webui\venv\lib\site-packages\ffmpy.py", line 93, in run
self.process = subprocess.Popen(
File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

File "C:\Stable Diffusion Files\stable-diffusion-webui\venv\lib\site-packages\ffmpy.py", line 98, in run
raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffmpeg' not found

This extension seems to have broken something about the ffmpeg connection on my system. When I'm running normal stable diffusion with extensions like controlnet and openpose, they now gives errors that they can't find ffmpeg.

How can I fix this issue? Thanks!

### Steps to reproduce the problem

Have controlnet and openpose installed, then install openOutpaint.

### What should have happened?

No ffmpeg issues

### Commit where the problem happens

Uninstalled

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

None

### AUTOMATIC1111 webUI Commandline Arguments

Default

**Comment by zero01101** [comment]
hey, so i genuinely can't imagine how this could've had anything to do with openOutpaint; we don't touch anything even close to ffpmeg, and in fact don't even have any additional python requirements with the extension version - all the extension does is host an iframe that containts the HTML/JS for openOutpaint.  i poked around in openpose editor's repo and didn't see anything suggesting ffmpy/ffmpeg was referenced in recent commits, but i could certainly be missing that... 

in any case, it appears that [you've confirmed it's unrelated to openOutpaint in the A1111 discussion](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8211) as well, so i'm gonna close this one as "uh, sorry, but that's not our doing"
