### ISSUE TITLE
[Feature Request]: Put Smooth rendering in Settings tab

### ISSUE THREAD

**Issue by younyokel** [zero01101/openOutpaint#214]
Smooth rendering is a visual option that does not affect the output, so I think its place on the Settings tab will be quite suitable.

**Comment by younyokel** [comment]
Also, I noticed that it resets once sometimes so maybe it won't in the settings tab as a global option?

**Comment by zero01101** [comment]
i think it makes sense, leaving the issue open so i get around to this eventually :)

**Comment by zero01101** [comment]
updated in https://github.com/zero01101/openOutpaint/commit/5fb01c901f36cb911299ce5bca2cdd6accbeed95
