### ISSUE TITLE
[Feature Request]: add button to reset zoom canvas to 1

### ISSUE THREAD

**Issue by amokiller** [zero01101/openOutpaint#221]
### Is your feature request related to a problem? Please describe.

is it possible to add a button to reset the zoom to level 1?
When you zoom with the mouse you can't always go back to level 1 and the image doesn't look completely good.

I'm use Chrome console with "viewport.zoom =1", after  move canvas a bit with CTRL + mouse left click, and zoom is restored.

Maybe you can add this like a button.

Thanks.

### Describe the solution you'd like

Add button and/or shortcut key to reset zoom

### Proposed workflow

--

### Describe alternatives you've considered

--

**Comment by zero01101** [comment]
genuinely mind-boggling that it wasn't added this entire time, too :| 

somewhat hastily added in https://github.com/zero01101/openOutpaint/commit/64bc673f45bca1970280cb330b4116ec31ee87ed, look on the layers palette header for the reset zoom button :)

**Comment by amokiller** [comment]
i love you ❤
