### ISSUE TITLE
[Feature Request]:  Mirror selected image region (horiz+verti)

### ISSUE THREAD

**Issue by GeorgLegato** [zero01101/openOutpaint#223]
### Is your feature request related to a problem? Please describe.

If in/outpainting 360-panoramas left edge and right edge needs to be seamless.
On txt2img we can use Assymetric Tiling-X ok, but after upscael the Tiling-X is lost.

The great outpuaint extension can help here, see screenshot.
Need to copy right edge to the left, mirror X, mask and repaint this area to get rid of seam. same on the other edge

![image](https://user-images.githubusercontent.com/7210708/230725679-29359ff8-96b6-4ef2-826b-f96992136d57.png)

### Describe the solution you'd like

When in select area mode (where you can move, rotate, scale) that area, add something to mirrot the selection.
Maybe like add add an icon next to the knob to rotate the selection.?

### Proposed workflow

try to edit a 360-flatted image

### Describe alternatives you've considered

none

**Comment by seijihariki** [comment]
Hello, almost sure we do have a mirror for stamps, but I do agree that it would be a good idea to add the functionality to basic selection as well.

For now, you can add it as a resource, and use the mirroring there. Will send a pull soon to fix this.

**Comment by seijihariki** [comment]
@GeorgLegato Just created a testing pull request. If you could try the branch and validate if the implementation works, it would be great!

**Comment by GeorgLegato** [comment]
i used "gh pr 223" and have a local folder "outpaint" in my extension folder
restarting webui does not show the outpainting tab. 
how different is the dev repo vs the release one?
once up, i test the mirror feature

**Comment by seijihariki** [comment]
You should have to check the branch on the app directory directly, as no changes were made to the actually extension, only to the web App.

**Comment by GeorgLegato** [comment]
I only know the extension. never touched or read the app only, I assume repo "outpaint" is the webApp, where I have no clue how to start it. local copy of "outpaint" is on branch224. could not find in readme how to start actually. thx

**Comment by GeorgLegato** [comment]
@seijihariki 
I did it... the outpaint.bat was it...
ok, selection on image is doing well
![image](https://user-images.githubusercontent.com/7210708/230794434-fd781dba-4823-4987-91a7-868bfaa7a378.png)
