### ISSUE TITLE
[Bug]: Imageis degraded after each generation

### ISSUE THREAD

**Issue by ZZZephyriusss** [zero01101/openOutpaint#229]
### What happened?

After each inpaint or outpaint, the overall quality is degraded, like a blur filter is applyed each time. It is applied in all the selected square even if only partial inpaint is asked. It happens withinpainting and out painting too.
ps : my version is update, i have put all the blur option to zero.

![openoutpaintbugreport](https://user-images.githubusercontent.com/131444123/233779595-6b85142f-a618-46c2-91e7-afc4bb2224d2.jpg)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ... [etc]

### What should have happened?

In outpaint mode, the quality of the image stay the same, only the outside border is affected. In inpaint mode, only the red area is affected.

### Commit where the problem happens

the last one, and this happen for the last commuts too

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Browser Extensions/Addons

addons : adblock, always on top,

i tested it with chrome and it happen too.

some times when a put on "synch cursor size", and then i uncheck it, it stoped to do it....and after some generations, it turns back to it randomly. 

### AUTOMATIC1111 webUI Commandline Arguments

--api --xformers

### Additional information

it seems like it is layer ralated because everytime it happen,  and i try to put the master layer on top again  then a flat the image, everything is mess up, and if i save it, only the last generation is saved and not the flatten layer. The only way to save it correctly is by making a selection and save "visible"...but even that some times fails, because it is saved but the layers are not in the same order as it is expected.

Anyway, i really want to thank you and your teram : i looooove your app, it is incredible, by far the best, even if it is less fancy than Invoke, it is much more conveniant and powerful. thanks

**Comment by zero01101** [comment]
so i think exactly what you're looking for is going to be taken care of via the "keep unmasked" toggle (pushpin icon) :)

![image](https://user-images.githubusercontent.com/1649724/233843483-21341a92-5257-48d8-9c7e-50b7fe72ed3d.png)

**Comment by ZZZephyriusss** [comment]
@zero01101 here the screenshot, i have try everything, keep unmak on or off,  put at the value zero or at the max, every generation  the image outside is beeing blurred :


![openoutpaintbluuryprblm](https://user-images.githubusercontent.com/131444123/234627772-c093c79a-4228-43c1-a958-8de5203d7f73.png)

**Comment by ZZZephyriusss** [comment]
really sorry to annoy you, but i thing it really is a probleme . thanks for your attention anyway . really love your App

**Comment by zero01101** [comment]
sorry for the delay; out of curiosity, did you try that with the keep unmask option enabled? your image implies that you left it disabled which, yeah, that'd do nothing lol... the blur radius sets the amount of gaussian blur around the inpaint mask to blend the original vs returned inpaint but will only do anything if the option is enabled ;) 

see https://github.com/zero01101/openOutpaint/issues/99 for further detail/info - it seems to be exactly what you're experiencing, and is precisely why the keep unmasked option was implemented :)

**Comment by zero01101** [comment]
closing as stale for now
