### ISSUE TITLE
[Bug]: Save Workspace doesn't appear to be working correctly

### ISSUE THREAD

**Issue by BowTiedZorro** [zero01101/openOutpaint#232]
### What happened?

After generating an image, I saved the workspace. After doing some additional outpainting on top of that, I wanted to save again, so I clicked the floppy disk icon to save. Didn't get a popup to save the filename, so I guessed that it saved under the same name. Later, did a refresh, and lost the work that occurred after the first save.

I manually reproduced this sequence of events with the console open, and noticed an error during the second save:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at workspaces.put.onsuccess (workspace.populate.js?v=2aea61f:101:60)
workspaces.put.onsuccess @ workspace.populate.js?v=2aea61f:101
IndexedDB (async)
workspaces.get.onsuccess @ workspace.populate.js?v=2aea61f:100
```

Then, I tried to delete the workspace that was initially created on the first save and I see this error:

```
Uncaught (in promise) DOMException: Failed to execute 'delete' on 'IDBObjectStore': The transaction has finished.
    at workspaces.get.onsuccess (http://127.0.0.1:7860/file=extensions/openOutpaint-webUI-extension/app/js/initalize/workspace.populate.js?v=2aea61f:180:23)
workspaces.get.onsuccess @ workspace.populate.js?v=2aea61f:180
```

### Steps to reproduce the problem

1. Go to openOutpaint via A1111 extension in Chrome. Open the console in DevTools
2. Generate an image via the Dream tool
3. Save the workspace and give it a name
4. Outpaint the image
5. Try to save the workspace again.
6. See the first error in the console: `Cannot read properties of undefined reading ('name')`
7. Try to delete this workspace
8. See the second error in the console: `Failed to execute 'delete' on 'IDBObjectStore': The transaction has finished.`

### What should have happened?

I think what should have happened was either the current workspace gets updated when the new data, or a new popup dialog box opens up with the current workspace name/ability to add a new name.

### Commit where the problem happens

5e84d6d5

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

No extensions installed

### AUTOMATIC1111 webUI Commandline Arguments

--allow-code --xformers --enable-insecure-extension-access --api --port 7860 --cors-allow-origins=http://localhost:7860

### Additional information

Screenshot of console after going through the above sequence of steps:

![screenshot-workspace-error-messages](https://github.com/zero01101/openOutpaint/assets/84651381/610a16bf-1134-47c4-84d3-fbcdc2471bb2)

**Comment by zero01101** [comment]
terribly sorry for the extended delay; this project isn't abandoned but i've had to step away from it due to Reasons for a while, and i admit additional responses may (aka will probably) be delayed but hopefully not nearly as long

confirming issue experienced here, will definitely look into this, my apologies for the trouble :( can't exactly provide an ETA due to aforementioned Reasons but i just wanted to at least respond that this is noted with regrets

**Comment by zero01101** [comment]
fixed in https://github.com/zero01101/openOutpaint/commit/b369d3cfcfccf66462b5c6bb131e781f47ed4725
