### ISSUE TITLE
Send to openOutpaint button not working again

### ISSUE THREAD

**Issue by aaron9412** [zero01101/openOutpaint#233]
### What happened?

Clicked send to openOutpaint from img2img, openOutpaint displayed with a blue empty square

### Steps to reproduce the problem

Load something in img2img, generate, click "send to openOutpaint"

### What should have happened?

Image loaded in openOutpaint

### Commit where the problem happens

5e84d6d5

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Browser Extensions/Addons

openOutpaint-webUI-extension	https://github.com/zero01101/openOutpaint-webUI-extension.git	5e84d6d5 (Mon Apr 10 23:01:41 2023)	latest
sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor	f2d5aac5 (Sat Apr 15 13:21:06 2023)	latest
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	c9c8ca6e (Sun May 7 17:15:00 2023)	latest
sd_dreambooth_extension	https://github.com/d8ahazard/sd_dreambooth_extension.git	926ae204 (Fri Mar 31 15:12:45 2023)	new commits
LDSR	built-in		
Lora	built-in		
ScuNET	built-in		
SwinIR	built-in		
prompt-bracket-checker	built-in

### AUTOMATIC1111 webUI Commandline Arguments

--api --cors-allow-origins=http://127.0.0.1:7860

### Additional information

It worked before I added command line arguments. Copying and pasting works and is a workaround. Thank you for making this!

**Comment by aaron9412** [comment]
It works in chrome!

**Comment by aaron9412** [comment]
it started working again after I opened a111 in chrome but I am getting black images with img2img and really bad borders with dream. I don't have this issue when using the outpainting mk2 script in a1111

**Comment by Kadah** [comment]
I found that I always need to reload it's extension tab the first time starting A1111 for it to work.

**Comment by expection1985** [comment]
I also get black image at the extend region , and not use firefox

**Comment by zero01101** [comment]
so sometime around firefox v115, everything Magically Started Working Again with no changes on my end soooo i'm closing this as stale... 

anyone still having issues with black regions, please file a new issue along with the issue template after trying in a different browser or with extensions disabled as there are some (i.e. duckduckgo privacy) that play havoc with canvas elements
