### ISSUE TITLE
[Bug]: floating control panel doesn't showing up in lobe-theme ext.

### ISSUE THREAD

**Issue by Aincvy** [zero01101/openOutpaint#237]
### What happened?

As the title.

![image](https://github.com/zero01101/openOutpaint/assets/8110347/65965af5-2d51-4119-bd27-d24364752694)

### Steps to reproduce the problem

1. Install ext from sd webui ext tab.
2. restart ui
3. click `Open Outpaint`

### What should have happened?

Left control panel should be visible.

### Commit where the problem happens

commit/5e84d6d5b1057f837eeecaa49a92a235dd589bc5

### What platforms do you use to access openOutpaint?

Windows, Linux

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

![image](https://github.com/zero01101/openOutpaint/assets/8110347/9df430b7-38af-45d5-8083-15f5bcf0a592)

### AUTOMATIC1111 webUI Commandline Arguments

webui-user.sh:  `--listen --enable-insecure-extension-access --theme dark --xformers`

launch.py: `--listen --api`

### Additional information

`sd-webui-lobe-theme` and `sd-web-ui-kitchen-theme`, none of it works.

If I disable them all, then it works.

![image](https://github.com/zero01101/openOutpaint/assets/8110347/73849021-626f-4f07-9d70-e6f466276e69)

**Comment by Aincvy** [comment]
Change lobe theme settings `Fixed -> Float` , then it's visible. 

![image](https://github.com/zero01101/openOutpaint/assets/8110347/bc17cf2b-644d-4c8a-84e4-928f667b0813)

Close this.

**Comment by zero01101** [comment]
good to know at least, thanks!
