### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 2blackbar** [zero01101/openOutpaint#240]
### Is your feature request related to a problem? Please describe.

Can you add support for controlnet inpaint ? IT will improve results by a lot
https://github.com/Mikubill/sd-webui-controlnet/discussions/1464

### Describe the solution you'd like

controlnet inpaint model support that lets user inpaint with any model and results are better than inpainting models 

### Proposed workflow

.

### Describe alternatives you've considered

.

**Comment by zero01101** [comment]
https://github.com/zero01101/openOutpaint/commit/071ed031f188595cd1605df836e70b864e608670 🤞
