### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by garin210** [zero01101/openOutpaint#245]
### Is ths issue about the extension?

- [X] Yup, this is for sure about the extension

### What happened?

[errorMessage.txt](https://github.com/zero01101/openOutpaint-webUI-extension/files/11409432/errorMessage.txt)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ... [etc]
in webui i imported an image for outpainting. when i select an area and clicked i got an error.

### What should have happened?

it should work as it should

### Commit where the problem happens

22bcc7be428c94e9408f589966c2040187245d81

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Browser Extensions/Addons

canvas zoom
clip interrogator
deforum
dynamic prompt
webui 3d open pose editor
webui aspect ratio helper
webui controlnet
dreambooth extension
webui chagpt utilities
webui image browser
webui inspiration
upscale for automatic1111

### AUTOMATIC1111 webUI Commandline Arguments

--api --xformers --opt-sub-quad-attention

**Comment by zero01101** [comment]
closing as stale
