### ISSUE TITLE
How to use sdxl without automatic1111

### ISSUE THREAD

**Issue by gitihobo** [zero01101/openOutpaint#251]
I just want a quick and easy way to use outpainting with sdxl without needing to load automatic1111 or have internet nearby. How do I properly do that?

**Comment by zero01101** [comment]
uh... well stable diffusion certainly requires **some** kind of inference engine... if you don't want to run A1111 then something like [invoke ai](https://github.com/invoke-ai/InvokeAI) or [comfyUI](https://github.com/comfyanonymous/ComfyUI) or [stable studio](https://github.com/Stability-AI/StableStudio) but i can't really help you there

**Comment by gitihobo** [comment]
so its not possible to just run the model without anything?

**Comment by zero01101** [comment]
couldn't imagine how you would; it's kind of like trying to make a crate engine take you somewhere without being attached to a chassis :)
