### ISSUE TITLE
[Feature Request]: Erase mask with Ctrl+left click instead of right click

### ISSUE THREAD

**Issue by rollzwiththepollz** [zero01101/openOutpaint#254]
### Is your feature request related to a problem? Please describe.

Is there a way you can implement Ctrl+left click to erase mask instead of right click? I need my right click for something else

### Describe the solution you'd like

See above

### Proposed workflow

See above

### Describe alternatives you've considered

See above

**Comment by Kadah** [comment]
What is the something else?

**Comment by rollzwiththepollz** [comment]
I use a program called xGestures to do different things like alt-tab, ctrl-tab, etc. And that's bound to my right click

**Comment by rollzwiththepollz** [comment]
nvm i coded it myself, thanks

**Comment by zero01101** [comment]
hey, sorry for the delay; yeah, ctrl+click is already mapped to canvas panning because laptops don't have a clickable scrollwheel... beyond that, alt-clicking often has browser/OS shortcuts already defined, so it's kind of a minefield of "what CAN we use that'll work most of the time" :/
