### ISSUE TITLE
[Feature Request]: Make ControlNet more easy to use? or Provide info on how to use it in the Manual? 

### ISSUE THREAD

**Issue by Maki9009** [zero01101/openOutpaint#255]
### Is your feature request related to a problem? Please describe.

im very confused on how im supposed to use the reference controller mode

### Describe the solution you'd like

either explain on how to use it in the manual or make it more evident on how i can use them.. where do i reference images for it? 

### Proposed workflow

i feel like if i choose a certain control net just show up the settings or input image for referencing 

### Describe alternatives you've considered

explain how to use the current version

**Comment by zero01101** [comment]
yeah, manual update is overdue; my apologies :/  reference-only controlnet was a last-minute "well why not" add-on when putting together the inpaint processor and i'm not even sure if it works as i thought it would, or if it's even useful in this context as generally you'd supply it with an unrelated image to reference, and openOutpaint only passes the image directly under the reticle which is... kinda dumb and sort of tautological :/

**Comment by zero01101** [comment]
manual's updated :)
