### ISSUE TITLE
[Feature Request]: Keyboard shortcut for Mask Clear

### ISSUE THREAD

**Issue by rollzwiththepollz** [zero01101/openOutpaint#256]
### Is your feature request related to a problem? Please describe.

Can you please add a keyboard shortcut for clearing all masks on the canvas?

### Describe the solution you'd like

See above

### Proposed workflow

See above

### Describe alternatives you've considered

See above

**Comment by rollzwiththepollz** [comment]
nvm i coded it myself, thanks

**Comment by zero01101** [comment]
actually this is a great suggestion and probably should've existed in the first place; reopening to remind myself to do this lol

**Comment by zero01101** [comment]
(`[DEL]`) key now clears any drawn/painted masks, thanks for the suggestion 👍
