### ISSUE TITLE
[Bug]: Error generating images

### ISSUE THREAD

**Issue by softwareio** [zero01101/openOutpaint#267]
### Is ths issue about the extension?

- [ ] Yup, this is for sure about the extension

### What happened?

when executing [dream] the cmd displays images being generated and the GPU reflect generation like usage. But the images does not arrive to the UI, a error with the text "Error generating images" appears at the bottom right.

### Steps to reproduce the problem

1. Go to openOutpaint tab
2. Press dream and click anywhere in the screen

### What should have happened?

Image should have been displayed

### Commit where the problem happens

a4a0200f

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Browser Extensions/Addons

none

### AUTOMATIC1111 webUI Commandline Arguments

--api

### Additional information

Console:
![Screenshot 2023-10-28 192718](https://github.com/zero01101/openOutpaint-webUI-extension/assets/50053195/c81e523a-4b5c-4738-83e4-7a6b8f5d73df)
Network:
![Screenshot 2023-10-28 211615](https://github.com/zero01101/openOutpaint-webUI-extension/assets/50053195/89cefc29-374a-434c-b370-caf0c7de4612)

**Comment by zero01101** [comment]
disclaimer: apologies for the extended delay, my brain is terrible and you shouldn't expect much from me

try going to http://127.0.0.1:7860/docs#/default/text2imgapi_sdapi_v1_txt2img_post, click `try it out` and populate the request body input with 
```
{
	"batch_size": 1,
	"cfg_scale": 7,
	"enable_hr": false,
	"height": 512,
	"n_iter": 1,
	"negative_prompt": "test",
	"prompt": "test",
	"restore_faces": false,
	"sampler_index": "DDIM",
	"seed": "1",
	"steps": 1,
	"width": 512
}
```
and execute it -   it should return a base64 string if webUI's API is returning images successfully.  check the a1111 console logs for errors as well beyond the browser's console

**Comment by softwareio** [comment]
No worries, take your time if you have :).

this is the log level after testing the suggested, 
![image](https://github.com/zero01101/openOutpaint/assets/50053195/7e61c37e-d318-434c-b8ca-93e67967ab31)

The test, same outputput:
![image](https://github.com/zero01101/openOutpaint/assets/50053195/2ece612e-2079-40d1-aff9-4242ea104237)

**Comment by zero01101** [comment]
sorry again for delayed responses; the fact that you're receiving the same error in bare API calls unfortunately confirms that your issue is within A1111 somewhere, likely some extension you may have installed as well... i'd suggest maybe disabling all 3rd party A111 extensions and re-enabling one by one until you find the one that's causing havoc with your API availability :/
