### ISSUE TITLE
[Bug]: Img2Img/Dream leads to unexpected cropping

### ISSUE THREAD

**Issue by Balerion300** [zero01101/openOutpaint#269]
### What happened?

When using Dream or Img2Img, anything not inside the cursor window that is within the layer you're working on gets removed from the canvas. Images on the canvas on another layer than the current one stay in place, however.

This seems to be newish behavior, but it has been awhile since I last used OpenOutpaint. U have replicated this result in both Chrome and Edge. No apparent error messages are visible in the console.

### Steps to reproduce the problem

1. Go to OpenOutpaint
2. Dream a new image
3.  Move the cursor and dream or Img2Img overlapping the first image.
4. Accept one of the possible images, and anything outside the placement of the second cursor disappears from the canvas.

### What should have happened?

Images outside the cursor on the canvas should not be disappearing.

### Commit where the problem happens

https://github.com/zero01101/openOutpaint-webUI-extension@a4a0200f	

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Browser Extensions/Addons

None active (using Incognito mode to disable all extensions)

### AUTOMATIC1111 webUI Commandline Arguments

--api --xformers --no-half-vae --opt-channelslast

**Comment by zero01101** [comment]
disclaimer: apologies for the extended delay, my brain is terrible and you shouldn't expect much from me

yeah, confirming chromium-based browsers have a miserable new disaster with the layering implementation and that i'm not smart enough to have it figured out yet :/

**Comment by joshyy1312** [comment]
Got the same problem on chrome.

A  somewhat easy workaround is to click one of the previous steps in the history palette then click the last one again. Depending on your steps, you have to go farther back or not :)

Usually choosing a clear canvas or stamp does the trick. When you click on the last step it refreshes everything.

I still love this extension, I have a hard time picturing my SD workflow without it...

**Comment by zero01101** [comment]
seems chromium upstream is really seeming to be the culprit here; if anyone still affected could confirm the findings in https://github.com/zero01101/openOutpaint/issues/268#issuecomment-1848414152 that'd be awesome :)
