### ISSUE TITLE
[Bug]: Unable to Scroll Through UI Components

### ISSUE THREAD

**Issue by RaphaelNunes10** [zero01101/openOutpaint#275]
### What happened?

The UI components seem to have a static size that, despite having vertically stacked elements that make them grow in size past the boundaries of the screen, don't include a way to scroll down to access otherwise inaccessible elements.

### Steps to reproduce the problem

For example:

1. Go to the "openOutpaint" tab
2. Click on the "Stamp Image" tool
3. Keep uploading new images
4. The "Upload Images" button goes off-screen and can no longer be accessed

Or:

1. Go to the "openOutpaint" tab
2. Keep opening the expanding panels inside of the left-most UI component.
4. Many elements go off-screen and can no longer be accessed

### What should have happened?

The UI should either automatically resize to fit, which could be hard to implement and might not solve the issue, or otherwise include a functional scroll bar once the component grows past the screen boundaries, so the user can scroll up and down to be able to access all of it's elements.

### Commit where the problem happens

https://github.com/zero01101/openOutpaint/commit/2f3c65e28f064279eab5908d110e3a8449ee37b6

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Opera

### Browser Extensions/Addons

uBlock Origin, WindowAI

### AUTOMATIC1111 webUI Commandline Arguments

--autolaunch --xformers --api

### Additional information

![image](https://github.com/zero01101/openOutpaint/assets/43423924/3947f446-549f-436a-b626-5b39b0e16ae0)

**Comment by zero01101** [comment]
sorry for the delay - so unfortunately, given the vertical resolution of the screenshot, i can only sort of assume that's indicative of your desktop resolution as well and openOutpaint's been built around the expectation of at least full 1080p vertical space, and preferably at least 1440p- for what it's worth, there are scrollbars in the stamp content selector if the content overflows the pane size:

![stamp scrollbar](https://github.com/zero01101/openOutpaint/assets/1649724/c0985f60-3e30-4da4-97d5-316e8fe90dfb)

the main sections in the lefthand control region all have chevrons indicating their expansion status, i.e. you've got `prompts` and `save/upscaling` open currently.  the only real suggestion with current app scope is to "minimize" unnecessary/unused sections (i.e. the blank prompts section)
