### ISSUE TITLE
[Bug]: Not working with Forge

### ISSUE THREAD

**Issue by kamerosoul** [zero01101/openOutpaint#283]
### What happened?

I installed openOutpaint from Forge and looks fine, but when I go to Stable Diffusion tab and try to select a checkpoint or sampler, it is empty. And refresh does not do anything.  Forge is working fine, checkpoints, loras, embeddings, and general operation is working fine. But Openpaint does not load checkpoints.
Please help

### Steps to reproduce the problem

Install OpenOutpaint from forge
Run any promt text2image
Send to outpaint
select a checkpoint
Refresh not working, Model is empty (no options)

### What should have happened?

auto update Model field with A1111 settings

### Commit where the problem happens

version: f0.0.16v1.8.0rc-latest-240-ga0c89fae  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: 676f0d60c8

### What platforms do you use to access openOutpaint?

Windows

### What browsers do you use to access the UI ?

Opera

### Browser Extensions/Addons

Opera Ad Blocker

### AUTOMATIC1111 webUI Commandline Arguments

Forge:
set A1111_HOME=I:/stable-diffusion-webui
set VENV_DIR=%A1111_HOME%/venv
set COMMANDLINE_ARGS=%COMMANDLINE_ARGS% ^
--ckpt-dir %A1111_HOME%/models/Stable-diffusion ^
--embeddings-dir %A1111_HOME%/embeddings ^
--hypernetwork-dir %A1111_HOME%/models/hypernetworks ^
--lora-dir %A1111_HOME%/models/Lora

call webui.bat

**Comment by zero01101** [comment]
hey, so to my understanding forget doesn't really do anything different than A1111's API, but support for forge is still kind of not really there, it just "works" but hasn't had anything specifically written to accommodate forge in any way outside of what already exists for the A1111 API.  

that being said, i can't confirm what you're experiencing - however, i'm not using the @REM statements in webui-user, and set the COMMANDLINE_ARGS essentially as a copy/paste from A1111 webUI with a few additional flags it recommended on startup: 
```set COMMANDLINE_ARGS=--ckpt-dir "F:\storage\stable diffusion models" --vae-dir "F:\storage\stable diffusion VAEs" --lora-dir "F:\storage\loras" --api --api-log --cors-allow-origins=http://127.0.0.1:3456 --pin-shared-memory --cuda-malloc --cuda-stream```

with `--api-log` in there specifically, i can verify that (in firefox and chrome, at least, and opera being a chromium offshoot, chrome's rendering engine should be the same, but i admit i haven't tried opera) it does indeed not only list all available models but switches between them as expected 

```
[...]
API 2024-03-02 09:38:00.568045 200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.5057
API 2024-03-02 09:38:00.804992 200 http/1.1 GET /sdapi/v1/options 127.0.0.1 0.003
API 2024-03-02 09:38:06.690920 200 http/1.1 GET /sdapi/v1/sd-models 127.0.0.1 0.013
API 2024-03-02 09:38:06.805464 200 http/1.1 GET /sdapi/v1/options 127.0.0.1 0.003
API 2024-03-02 09:38:10.555750 307 http/1.1 POST /sdapi/v1/options/ 127.0.0.1 0.0
Loading weights [be1d90c4ab] from F:\storage\stable diffusion models\absolutereality_v16.safetensors
model_type EPS
UNet ADM Dimension 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Loading VAE weights specified in settings: F:\storage\stable diffusion VAEs\wd13-kl-f8-anime2.vae.pt
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  23148.51406097412
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  21670.306438446045
Moving model(s) has taken 0.19 seconds
Model loaded in 7.3s (unload existing model: 0.3s, load weights from disk: 0.3s, forge load real models: 6.2s, load VAE: 0.2s, calculate empty prompt: 0.3s).
API 2024-03-02 09:38:17.892553 200 http/1.1 POST /sdapi/v1/options 127.0.0.1 7.3328
[...]
```

any chance you could test it in a different browser, or possibly with the COMMANDLINE_ARGS filled out in the A1111 expected format? my uneducated guess is it's probably the `%A1111_HOME%` vars more than the browser

**Comment by kamerosoul** [comment]
Hi, sorry for delay.
I tested with Chrome and Firefox and have same problem
Also I noticed I have this in console when starting Forge:
[openOutpaint-extension-submodule] failed to download update, check network
But when checking extensions check for updates for openoutpaint have latest:
main 1c3a931c 2024-03-02 05:24:12 latest.
Any suggestion?

**Comment by kamerosoul** [comment]
Hi,
I found I missing --api in command line.
Sorry,
Now it is working fine

**Comment by seijihariki** [comment]
Will be closing this issue as solved! If you find any other issues, please file a new issue!
