### ISSUE TITLE
I'm having a problem using ControlNet In/Outpainting

### ISSUE THREAD

**Issue by marc2608** [zero01101/openOutpaint#291]
Hello, I've reproduced the steps in the "outpainting" video, which shows how to use ControlNet In/Outpainting with inpaint_only+lama pre processor and the control_v11p_sd15_inpaint model [ebff9138]. There's probably a detail or a little thing I can't figure out because I can't get outpainting. Every time I get random images that have nothing to do with the background image. (It could be a woman, a car, a house, an animal etc...) Can you tell me if I'm missing something, an important detail or something else? Here's photos of my session. Thank you in advance. 
![Capture d'écran 2024-08-07 170105](https://github.com/user-attachments/assets/044d34d7-79da-4071-bc64-9c97a330faa1)
![Capture d'écran 2024-08-07 170049](https://github.com/user-attachments/assets/73294764-44e0-4368-b40d-f6eac9848161)

**Comment by Nacho-sh** [comment]
Same problem here. I had this problem a year ago, the issue was that I hadn't installed the .yaml settings file for controlnet. However, I've reinstalled this and I can't get it to work. Check out if you've downloaded that file anyways.

**Comment by zero01101** [comment]
hey, so it looks like controlnet deprecated the `input_image` parameter a while ago and i'm a terrible project maintainer and didn't notice :/ should be updated and fixed now, sorry about that

**Comment by Nacho-sh** [comment]
Now, this is good service. Works perfectly now, thank you so much!

**Comment by marc2608** [comment]
Hi, 
I get this message in the CMD window (see photo). Can you tell me if there is a file in OpenOutpaint or in Controlnet that I can modify myself to make it work? 
![Capture d'écran 2024-08-09 181001](https://github.com/user-attachments/assets/17c80d4d-1956-4e57-a3e1-8234288529e2)

**Comment by zero01101** [comment]
> Hi, I get this message in the CMD window (see photo). Can you tell me if there is a file in OpenOutpaint or in Controlnet that I can modify myself to make it work? ![Capture d'écran 2024-08-09 181001](https://private-user-images.githubusercontent.com/132713311/356680184-17c80d4d-1956-4e57-a3e1-8234288529e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzY4OTQsIm5iZiI6MTcyMzIzNjU5NCwicGF0aCI6Ii8xMzI3MTMzMTEvMzU2NjgwMTg0LTE3YzgwZDRkLTE5NTYtNGU1Ny1hM2UxLTgyMzQyODg1MjllMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQyMDQ5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmY4YjNlMTY0NjQzM2M3YzUxMDIzMmI1YTgxYjFmNjgxNmQ2NjFiNTQ2ODA1NTY1MDJjMzU1MzBlNzg5Y2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GyZHPd6y4ac1kYN8xy9LpOkDtTg-_XEf91KL1bTDrUk)

yeah, that's precisely what the update is supposed to fix- i'm guessing you've pulled in the most recent updates? you can also go to the `debug info` section and check the version, if it's not reporting v20240808.001 then make sure you're fully up-to-date and try force-refreshing (shift? ctrl? one of them)+f5

**Comment by marc2608** [comment]
Sorry, it was a mistake on my part, a wrong reinstallation of the extension. With many thanks for having worked on and succeeded with such a well-made and powerful tool!
