### ISSUE TITLE
Insert a picture in the canvas

### ISSUE THREAD

**Issue by nightkall** [zero01101/openOutpaint#4]
Very nice tool, thanks for making it!

 I have a suggestion:

- Add a button to insert a picture from your PC in the canvas like in [Hua](https://github.com/BlinkDL/Hua), or paste it (Ctrl+V) from the clipboard.

Edit: I realized that it's on the to-do list.

**Comment by zero01101** [comment]
appreciate the kind words in any case, but i warn it'll likely take longer than it would a competent dev ;)

**Comment by zero01101** [comment]
implemented!

**Comment by nightkall** [comment]
wow, thanks!
