### ISSUE TITLE
Img2img tool seems to be broken

### ISSUE THREAD

**Issue by Kalekki** [zero01101/openOutpaint#47]
Clicking on the img2img tool doesn't bring up the new img2img tool with the cool masks, instead it errors 
![image](https://user-images.githubusercontent.com/1765167/203801712-8817e07a-90c9-4cbb-8024-5ff88398f830.png)
Was there supposed to be an option in the contextmenu that somehow didnt get added?
This is what's in the context menu when selecting img2img tool
![image](https://user-images.githubusercontent.com/1765167/203803905-4525cd71-6542-4204-96ea-6d4167b569f7.png)

**Comment by seijihariki** [comment]
Probably, I'll check during lunch.

**Comment by zero01101** [comment]
should be fixed in https://github.com/zero01101/openOutpaint/commit/ac5e43439e0a1b56243c522c750ecd7b8e0323fc :)
