### ISSUE TITLE
img2img marching ants persist if batch is rejected (bleeding edge branch)

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#63]
if you choose "N" after a batch of image mutations are presented, the marching ants become offended and refuse to leave the premises 

[ants.webm](https://user-images.githubusercontent.com/1649724/204930968-ea81b4f4-17ac-4a4d-8794-8bde27b65efd.webm)

**Comment by seijihariki** [comment]
Thanks, I noticed these remaining marching ants, but I could not spot exactly what was the cause. You telling me the issue was on img2img was enough to pinpoint the problem.

**Comment by zero01101** [comment]
confirmed fixed :)
