### ISSUE TITLE
upscale button only seems to work on selected layer (bleeding edge branch) 

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#68]
i could probably figure out why this happens myself but figured i should make an issue before i forget this happens

steps to reproduce:
 - make a picture
 - make a new layer
 - make something in that new layer
 - save canvas (not upscale)
 - upscale canvas 
 - select first layer
 - upscale canvas

regular save:
![2022-12-05 01 24 33 openOutpaint image](https://user-images.githubusercontent.com/1649724/205529825-aae3f350-cb94-4195-b46f-930200ccea58.png)

upscale before i knew what was happening:
![2022-12-05 01 24 37 openOutpaint image upscaler_R-ESRGAN 4x+](https://user-images.githubusercontent.com/1649724/205529846-fcd08aae-2651-4944-b358-bff7cb300161.png)

upscale after selecting base layer: 
![2022-12-05 01 25 15 openOutpaint image upscaler_R-ESRGAN 4x+](https://user-images.githubusercontent.com/1649724/205529860-870e1077-876c-4c45-ad27-94cf9525c372.png)

**Comment by seijihariki** [comment]
Check the download canvas code. That should be a good reference. To fix this you will have to use uil.getVisible which stacks and merges the layers (reference ui/floating/layers.js)

**Comment by zero01101** [comment]
perfect direction for getting me to actually fix a thing instead of waiting for Someone Else To Do It :D
