### ISSUE TITLE
layers UI could use a scrollbar (bleeding edge branch)

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#70]
**Is your feature request related to a problem? Please describe.**
the layers UI window needs a scrollbar because too many layers overflows it

**Describe the solution you'd like**
a scrollbar in the layers UI window

**Describe alternatives you've considered**
fewer layers? but telling people to not use the feature seems like a bad plan

**Additional context**
![image](https://user-images.githubusercontent.com/1649724/205545736-c374765e-e38b-49c4-99ea-06f17ed059ae.png)

**Comment by seijihariki** [comment]
Should be done on 87239d0

**Comment by zero01101** [comment]
i'm genuinely ashamed it was literally just that

i need to add CSS to [#terrible](https://github.com/zero01101/openOutpaint#terrible)

**Comment by seijihariki** [comment]
Well, CSS is indeed a strange beast
