### ISSUE TITLE
layer visibility toggle affects wrong layer (bleeding edge branch)

### ISSUE THREAD

**Issue by zero01101** [zero01101/openOutpaint#71]
**Describe the bug**
the eye icon to toggle layer visibility only affects the currently-selected layer, not the layer associated with toggle's row

**To Reproduce**
 - generate a dream
 - make a new layer
 - outpaint the dream
 - leaving the new layer selected, click the eye icon on the default image layer - it'll toggle the new layer instead

**Expected behavior**
appropriate layer is un/hidden

**Screenshots**
![layer visibility](https://user-images.githubusercontent.com/1649724/206044087-307feae7-cc70-43b8-b0a8-c90694813881.gif)

**Desktop (please complete the following information):**

- OS: win10x64 22h2 build 19045.2251
- Browser: firefox 
- Version: 107.0.1

**Additional context**
have done almost NO looking into it, my apologies, just something i noticed :/

**Comment by seijihariki** [comment]
Seems it was a bug introduced on the migration to history-supporting layers.

**Comment by seijihariki** [comment]
Should be fixed

**Comment by zero01101** [comment]
confirmed fixed
