### ISSUE TITLE
Model and Sampler dropdown list is blank.

### ISSUE THREAD

**Issue by Nesuhst** [zero01101/openOutpaint#85]
**Describe the bug**
Even though my auto111 instance has plenty of models, as well as the recommended inpainting model, nothing shows up and no generation happens when attempting to generate an image.

**Screenshots**
![Screenshot 2022-12-10 162450](https://user-images.githubusercontent.com/110304717/206878183-fe6bb178-f65a-4120-84dc-c35dec7cfb39.jpg)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser: brave
- Version auto ver. 44c46f0, openOutpaint ver. 0b2024d
- 
**Additional context**
I've read through the setup instructions. Didn't see anything related to my issue.

**Comment by seijihariki** [comment]
Brave browser? Will give it a look. Could you take some screenshots of the console after page reload?

**Comment by Nesuhst** [comment]
I might have to get a fresh re-install of openOutpaint. Now for some reason, It just stopped connecting to the page at all.
![Screenshot 2022-12-10 180313](https://user-images.githubusercontent.com/110304717/206880211-2e0c8f0c-8b3b-4a0d-9593-6c245e2ae41b.jpg)

**Comment by seijihariki** [comment]
Oh, that's very strange... If it works for you, you can try running `python -m http.server -b 127.0.0.1 3456`

This could end up solving the issue (it seems it is running on ipv6 after all)

**Comment by Nesuhst** [comment]
alright, that did something

![Screenshot 2022-12-10 181540](https://user-images.githubusercontent.com/110304717/206880507-c5f357ff-5b3f-4a42-bee1-ea3c8db5ef98.jpg)

**Comment by seijihariki** [comment]
Okay, can you try opening the console and reloading the page? Then just send a screenshot of it here.

**Comment by seijihariki** [comment]
Just tested in Brave... Seems to work here.

![image](https://user-images.githubusercontent.com/7552751/206880578-ba7a1c8a-9b50-42a0-a8b9-157661c09d94.png)

**Comment by Nesuhst** [comment]
![Screenshot 2022-12-10 182051](https://user-images.githubusercontent.com/110304717/206880629-812f806b-bde5-40ba-8529-40b0e1a87d9c.jpg)

**Comment by Nesuhst** [comment]
could it be the file structure I have setup in my auto111 copy?

**Comment by Nesuhst** [comment]
![Screenshot 2022-12-10 182327](https://user-images.githubusercontent.com/110304717/206880698-af7b36f4-d877-4bc6-9363-212b2974d009.jpg)

**Comment by seijihariki** [comment]
Oh, not that console!

This one:
![image](https://user-images.githubusercontent.com/7552751/206880674-eee80d18-9f35-4ee4-a14c-22341e857ace.png)

Sorry for not making it more explicit. It's (F12) to open devtools, then the console tab. 
After opening it, refresh the page and take a screenshot.

**Comment by Nesuhst** [comment]
![Screenshot 2022-12-10 182548](https://user-images.githubusercontent.com/110304717/206880753-dda20d74-8398-4d61-b4ed-5727892f9453.jpg)

**Comment by seijihariki** [comment]
Have you ran Automatic1111 webui with the --api command line flag? It seems the API is disabled from these errors...

**Comment by Nesuhst** [comment]
Alright. That's what it was. It's up and running

I'd accidentally skipped that when copying the line into my arg. Thanks for the help.

**Comment by seijihariki** [comment]
No problems, so this becomes more clear, added some functionality to #86 so we can now detect the lack of the API flag.
