### ISSUE TITLE
Prompts history

### ISSUE THREAD

**Issue by an303042** [zero01101/openOutpaint#87]
It would be nice to have an easy way to go back to a prompt I've recently used. That is all.

**Comment by seijihariki** [comment]
Hi! Do you think it would be better for the history to contain all information (styles, negative prompt and prompt) or each field have its own history? (styles in this case would probably not be included)

**Comment by an303042** [comment]
I would say give each field its own history, but maybe we can create some visual link between prompts that were generated together - either by numbering them, or coloring them, or some other preferably non ugly way?

**Comment by seijihariki** [comment]
Give it a look, please. It's on the testing branch (`git checkout testing`).

**Comment by an303042** [comment]
I think it looks great!

**Comment by seijihariki** [comment]
Great! Changes are now in the main branch. This issue will be closed as complete. For any other improvements/bug fixes, a new issue should be opened.

Thank you for your feedback!
