### ISSUE TITLE
Option to automatically adjust resolution when cursor size is changed

### ISSUE THREAD

**Issue by TiagoTiago** [zero01101/openOutpaint#90]
I understand that there may be situations where having a different resolution than the cursor size might be necessary; but it is inconvenient to have to keep setting things twice when you are ok with the resolutions matching; so it would be useful to have a checkbox to make both settings stay in sync.

**Comment by zero01101** [comment]
i'm inclined to agree that it should be a toggleable option; i'll look into this :)

**Comment by zero01101** [comment]
so it's trivial enough to add a checkbox and logic to dump the matched reticle size value to the SD resolution setting, but the actual slider element is giving me grief lol :D  

@seijihariki if there's a way to call a slider's `setValue` programmatically, i must be missing how to do so :/ any hints?

**Comment by seijihariki** [comment]
> so it's trivial enough to add a checkbox and logic to dump the matched reticle size value to the SD resolution setting, but the actual slider element is giving me grief lol :D
> 
> @seijihariki if there's a way to call a slider's `setValue` programmatically, i must be missing how to do so :/ any hints?

You should check the brush sliders because we set their value from the mouse wheel.

**Comment by zero01101** [comment]
think i overcame my terminal stupidity and got this working!  @TiagoTiago if you'd care to `git checkout i90` and see if this is what you were thinking of :)

**Comment by TiagoTiago** [comment]
Yep, exactly like that, thanx :)

----

Erm, sorry I didn't reply earlier, I thought I had clicked the submit button earlier, got distracted...

**Comment by seijihariki** [comment]
This feature should be complete. Closing this issue for now.
