### ISSUE TITLE
Allow non-square cursor and resolution

### ISSUE THREAD

**Issue by TiagoTiago** [zero01101/openOutpaint#91]
Sometimes you might wanna generate something in a long/thin area and shouldn't need to waste memory/processing power with a bunch of pixels are are not considered relevant. I think it would be good to have the option of setting non-square dimensions for the cursor and resolution.

**Comment by zero01101** [comment]
hah, "discrete x/y axes for reticle" has actually been on the [//todo](https://github.com/zero01101/openOutpaint/wiki/todo) for a while :) one of these days i'll stop ignoring that one...

**Comment by seijihariki** [comment]
This one will be... a bit interesting to implement. Mainly because, when scaling the cursor, the number on the slider should represent the horizontal or vertical resolution of the cursor? We could display both on the slider bar, but only one would be text-editable.

**Comment by zero01101** [comment]
i honestly kinda wonder if this should be an entirely different tool, similar to the marquee selector; just drag over the region to dream over and probably some kind of input confirmation?

**Comment by TiagoTiago** [comment]
Maybe click uses the currently set size, and click-and-drag will resize relative to the currently set size, possibly with a confirm button at the end? Though, it could be useful to also have the option of setting the size you want by typing and/or with sliders as well.

**Comment by seijihariki** [comment]
Well, we do have some events from the mouse lib that can differentiate a drag from a click, so this could be something relatively easy to implement.

Just some qualms over the actual generation resolution though. Maybe we can assume drag areas will be one-to-one...

**Comment by TiagoTiago** [comment]
> Just some qualms over the actual generation resolution though. Maybe we can assume drag areas will be one-to-one...

Personally, I think it would be intuitive if that was the default. Perhaps even have the checkbox from #90 be checked by default?

**Comment by seijihariki** [comment]
We could do that, actually. I feel like #99 is confusion due to this functionality, and anyway, the settings are saved in local storage, so one would only have to change that once.

**Comment by seijihariki** [comment]
From 3ef2bce sync is default.

**Comment by seijihariki** [comment]
@TiagoTiago please check if this (fb83b12) is okay for now It's on `testing` branch as well. If you find any issues using the tool, please tell us here. For now, supports only one-to-one resolution. Drag creates an area, left click accepts, right click resets.

Plans to support changing the resolution for this is on the board, but not implemented yet.

**Comment by TiagoTiago** [comment]
Showing some sort of indicator of what to do to confirm/cancel the area selection would probably be a good idea, since not all users will read documentation and stuff.

**Comment by seijihariki** [comment]
I think this would start polluting the cursor quite a bit... We can try adding a status bar like in blender, photoshop and krita:

![image](https://user-images.githubusercontent.com/7552751/207443961-8bdd3e7c-9043-4a8c-8a7f-5c1253f6ca7a.png)

Some status and error messages could also use this, so wouldn't be just for control overview.

**Comment by TiagoTiago** [comment]
Maybe use the same menu system that's used for interacting with new generations, and for interrupting/canceling unfinished ones?

**Comment by TiagoTiago** [comment]
Or perhaps like the text that indicates the size of the cursor on the canvas?

**Comment by seijihariki** [comment]
Yeah, that's what I was trying to avoid... Putting much more stuff in the cursor, especially considering these instructions are useful for someone's first time using the tool, but kind of becomes a hindrance afterwards.

**Comment by TiagoTiago** [comment]
Status bar would be an welcome addition though. But probably a good idea to make it optional for people that wanna maximize screen space.

**Comment by seijihariki** [comment]
Yeah, I'm thinking that 25px would not be a huge loss. Still, a way to make it act like a windows bar and show only when there is a new notification or something like that would be best. I was even thinking of making some of the floating windows optional, as not everyone wants their screen occupied by the layers window, specially when doing a quick sketch/generation.

**Comment by seijihariki** [comment]
And many people would be okay with just ctrl-z and ctrl-y without the need to see the full history.

**Comment by seijihariki** [comment]
Maybe now it is more intuitive? It functions like other area interactions now. Hover converts cursor into pointer, it interacts more clearly with already generated images. Selection acceptance now requires a click inside the area itself.

**Comment by seijihariki** [comment]
Will consider this as done for now. Status bar is in development, but will take a bit. The changes done to the drag select interface should make it intuitive enough for now.

**Comment by mpmo10** [comment]
You can select non square Dream (D)? How?

**Comment by zero01101** [comment]
sure can, just pull in the latest updates to the main branch, select the dream tool, drag-n-drop any arbitrary rectangle of your choosing, and click inside it to confirm your region :)
