### ISSUE TITLE
[Feature] Keep Original Mask Contents

### ISSUE THREAD

**Issue by mpmo10** [zero01101/openOutpaint#99]
**Describe the bug**
When I try to inpaint an image and I make the square more than 512px, the image inside the square becomes lower res. I like making the "D" (Dream) square bigger because the bigger it is, the better the inpainting will be since the AI will have a clearer understanding of the whole image.

**To Reproduce**

Upload an image, inpaint part of it with the Mask Brush (M) tool, make the generation Dream (D) square 1024px (or any res higher than 512px, but 1024px is the most obvious) instead of the default 512px square by moving the mouse scroll wheel upwards, generate an image and compare before and after of what's inside the box.

**Expected behavior**
For the image that's not been masked and that's inside the "D" Dream square box not to become lower res and stay the same after generation

(First image is before generation, second image is after). See how the stars and city lights are lower res. This doesn't happen when the square is 512px. Even if I increase the square, the unmasked image inside the square shouldn't be affected but as you can see it is being affected

![Screenshot (880)](https://user-images.githubusercontent.com/52265226/207221561-8d0f8bd8-dc46-44bd-a02d-9de4e8b4854f.png)
![Screenshot (881)](https://user-images.githubusercontent.com/52265226/207221588-6598cfbb-0178-4d2b-98b6-29922d069917.png)

**Comment by zero01101** [comment]
i suspect you're running into the decoupled reticle/SD resolution, which is actually by design but has a [PR](https://github.com/zero01101/openOutpaint/pull/98) and [related issue](https://github.com/zero01101/openOutpaint/issues/90) which syncs the resolution to the cursor and vice versa.  

with the current main-branch version (v0.0.9.6), if you expand the stable diffusion settings and set the resolution value to match your reticle size, does the output match your expectations?

**Comment by mpmo10** [comment]
Try inpainting a 1920x1080 image. Then choosing 1024px square, inpaint, then download the canvas. Now open the original and the new canvas images in your pc’s photo gallery and quickly switch between the two and focus on the image where the square was. Do you not see a lower res in the new canvas compared to the original? Download the two images I uploaded and quickly switch between them using your pc’s photo viewer, you’ll see a clear degradation in res for the new canvas

**Comment by seijihariki** [comment]
Have you changed generation resolution as well as cursor size when inpainting?

**Comment by mpmo10** [comment]
> Have you changed generation resolution as well as cursor size when inpainting?

You mean this right? I get horrible inpainting results if I increase this value. I think because the inpainting model has been trained on 512x512 images so it's best not to change this value 
![2022-12-13 20_08_04-openOutpaint 🐠](https://user-images.githubusercontent.com/52265226/207384589-b655face-c69e-425d-846f-5aa1790efbdf.png)

**Comment by mpmo10** [comment]
> > [instructions]  Do you not see a lower res in the new canvas compared to the original?
> 
> honestly, i sure don't in my output :/ no argument that there's a significant difference in your screenshots at all however
> 
> first image was an imported 1920x1080 screenshot just simply as-is using the save canvas button, second was, uh, after turning the opponent into a ""football"" with the color brush, third is a pathetic attempt to get a hot dog out of the oppopnent using the mask brush lmao ![2022-12-13 05 10 28 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233117-58f7bde7-9a21-482a-a24b-ccd312926c53.png) ![2022-12-13 05 18 37 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233127-3554342a-dd85-40ed-bc75-62a8deab6671.png) ![2022-12-13 05 24 06 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233827-ec424a35-f8f2-4ae9-862d-45712a8ed0d2.png)

Yeah there's no degredation in quality for the pics you uploaded. Hmm. Are you sure you increased the Dream (D) canvas size from 512px to higher (while keeping the resolution, which is under 'Stable Diffusion Settings' at 512 resolution) ?

**Comment by mpmo10** [comment]
> > [instructions]  Do you not see a lower res in the new canvas compared to the original?
> 
> honestly, i sure don't in my output :/ no argument that there's a significant difference in your screenshots at all however
> 
> first image was an imported 1920x1080 screenshot just simply as-is using the save canvas button, second was, uh, after turning the opponent into a ""football"" with the color brush, third is a pathetic attempt to get a hot dog out of the oppopnent using the mask brush lmao ![2022-12-13 05 10 28 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233117-58f7bde7-9a21-482a-a24b-ccd312926c53.png) ![2022-12-13 05 18 37 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233127-3554342a-dd85-40ed-bc75-62a8deab6671.png) ![2022-12-13 05 24 06 openOutpaint image](https://user-images.githubusercontent.com/1649724/207233827-ec424a35-f8f2-4ae9-862d-45712a8ed0d2.png)

Are you sure you're increasing the canvas size? Watch this vid, this is I what I'm doing exactly: https://streamable.com/zv7wpi

I attached before generation and after generation pics below. You can see a clear degredation in quality of the stuff that was inside the box

Before:
![207233117-58f7bde7-9a21-482a-a24b-ccd312926c53 (1)](https://user-images.githubusercontent.com/52265226/207388193-22271c09-d5ce-42b3-898e-1e83b9bae6a1.png)

After:
![2022-12-13 16 18_10 openOutpaint image](https://user-images.githubusercontent.com/52265226/207388296-30bfa272-5f3d-4b71-9ea9-ffe5512f5262.png)

**Comment by mpmo10** [comment]
> If you are refering to the unmasked regions (that should not be modified)

"If you are refering to the unmasked regions (that should not be modified)" yup that's exactly what i'm referring to. I understand the masked region will be a little lower res and that's fine, but if you can add an option to keep the unmasked regions completely the same that would be perfect!

**Comment by seijihariki** [comment]
> > If you are refering to the unmasked regions (that should not be modified)
> 
> "If you are refering to the unmasked regions (that should not be modified)" yup that's exactly what i'm referring to. I understand the masked region will be a little lower res and that's fine, but if you can add an option to keep the unmasked regions completely the same that would be perfect!

That makes sense... Will check what it would take to implement this. Probably will only really apply to fully opaque masking to avoid dealing with averaging the images. Would that be okay to you?

**Comment by mpmo10** [comment]
> > > If you are refering to the unmasked regions (that should not be modified)
> > 
> > 
> > "If you are refering to the unmasked regions (that should not be modified)" yup that's exactly what i'm referring to. I understand the masked region will be a little lower res and that's fine, but if you can add an option to keep the unmasked regions completely the same that would be perfect!
> 
> That makes sense... Will check what it would take to implement this. Probably will only really apply to fully opaque masking to avoid dealing with averaging the images. Would that be okay to you?

Yup that would be good, thanks a lot

**Comment by seijihariki** [comment]
This is not a bug anymore, but a feature request. We have to implement a feature to reapply masked surfaces to the image received from the remote before displaying them to the user (probably controlled by a checkbox or something). - Keep-masked maybe?

**Comment by zero01101** [comment]
yeah, i definitely missed the context of 512px render resolution with the larger reticle, my fault on that one, and agreed it _shouldn't_ replace anything that isn't masked, but yeah, as mentioned, stable diffusion itself is just working off of a 512x512 area at that point and we're simply replacing the previous high-res content with the new low-res response... 

as a crappy workaround for now, you could put the wrong-resolution masked inpaint/img2img on a new layer and erase away the undesirable bits? 
![lil bad pokerface](https://user-images.githubusercontent.com/1649724/207463617-44c246d3-f306-4ed7-9117-d7daa83324f7.png)

**Comment by seijihariki** [comment]
Hi, @mpmo10, can you check if the implementation is okay for this feature? It's on the `testing` branch (`git checkout testing`).

An option was added, and is enabled by default, where all fully masked pixels on the original image are kept.

**Comment by mpmo10** [comment]
> Hi, @mpmo10, can you check if the implementation is okay for this feature? It's on the `testing` branch (`git checkout testing`).
> 
> An option was added, and is enabled by default, where all fully masked pixels on the original image are kept.

Tried it just now, yes perfect! thanks a lot. But I do notice that when I have "Keep Masked" off, it does a better job at blending in the edges of the masked with unmaked. But when the "Keep Masked" is turned on, you can see the lines of where the mask brush has been more clearly. Is there a way to make it blend in more when "Keep Masked" is turned on? I tried increasing the "Mask blur" to 20 but even at that high value the edges of the masked and unmasked parts don't blend in that well as when "Keep Masked" is off. And going higher than 30 Mask blur makes the inpainting generations worse for some reason

**Comment by seijihariki** [comment]
Well, that's kind of to be expected, as we have a very crisp original image right beside an area of the image that was generated at low res.

We can try adding a keep image blur slider if you want, but it will be a simple gaussian blur, so I do not guarantee that it will be anywhere near good.

**Comment by mpmo10** [comment]
> Well, that's kind of to be expected, as we have a very crisp original image right beside an area of the image that was generated at low res.
> 
> We can try adding a keep image blur slider if you want, but it will be a simple gaussian blur, so I do not guarantee that it will be anywhere near good.

Yeah a gaussian blur slider would be great 🙏🏼 (even better if changing the slider would change the image in real time)

**Comment by seijihariki** [comment]
If you have any other ideas for implementation, please tell us so we can try!

For now, will implement a slider for blur, but that's the only thing that we can do for now.

**Comment by seijihariki** [comment]
> Yeah a gaussian blur slider would be great 🙏🏼 (even better if changing the slider would change the image in real time)
 In real time... would be kind of difficult, considering now we have multiple concurrent generations/image picking. This pull will include a non-realtime implementation, but will see what I can do in the future.

**Comment by seijihariki** [comment]
Check now the testing branch.

**Comment by mpmo10** [comment]
> Check now the testing branch.

![2022-12-15 20_25_25-openOutpaint 🐠](https://user-images.githubusercontent.com/52265226/207914488-24c704ad-e777-4c85-9113-440e9aaf9c89.png)

Is it supposed to be here? I've selected the Dream (D) button, not the img2img (i) button

**Comment by seijihariki** [comment]
I imagine you ran `git pull` already.

**Comment by mpmo10** [comment]
> I imagine you ran `git pull` already.

Aha ok I see it. Yess it does work. Thanks for adding this feature!!
